### ISSUE TITLE
使用自定义的boomer，new一个后再quit，Socket连接还在

### ISSUE THREAD

**Issue by mao303mao** [myzhan/boomer#101]
我想使用自定义的boomer进行灵活的启动及关闭，但是发现new一个后再quit，Socket连接还在。
以至于多次后，很多quit的boomer一直在连接master。
![image](https://user-images.githubusercontent.com/37785668/94637431-1f9ef700-030a-11eb-8538-85cd75a495f5.png)

**Comment by myzhan** [comment]
多谢，麻烦拉一下最新代码，看看是否已经修复。

**Comment by mao303mao** [comment]
已经ok，我自己也是这样改的
