### ISSUE TITLE
boomer 运行一段时间后，CPU使用率骤增，然后会结束压测

### ISSUE THREAD

**Issue by Manoner** [myzhan/boomer#103]
**Describe the bug**

**To Reproduce**
1. 启动 locust master(version 1.3.0)
2. 运行作者示例程序example/ratelimit/maxrps 下代码（StableRateLimiter限速模式），限速设置200/s，
`rateLimiter := boomer.NewStableRateLimiter(200, time.Second)`
3. locust设定用户 Number of users to simulate ：10000，Spawn rate: 100/s
4. 压测程序执行一段时间后，CPU突然升高，请求急剧下降（有时会导致spawn的goroutine全部结束，压测停止）。见图所示
5.

**Expected behavior**
为什么在压测过程中，CPU的使用率会急剧升高呢？（目前没有找到规律和发生的原因）

压测过程中出现意外停止的时候，Python locust master端会提示
``

**Screenshots**

![Snipaste_2020-10-22_15-11-11](https://user-images.githubusercontent.com/60100619/96839357-a499ae00-147b-11eb-8a3f-51a7d0b7be53.png)
![Snipaste_2020-10-22_15-11-28](https://user-images.githubusercontent.com/60100619/96839378-ae231600-147b-11eb-90b7-93cdc6764e16.png)

图片地址：
[http://cdn.note.manoner.com/Snipaste_2020-10-22_15-11-11.png](http://cdn.note.manoner.com/Snipaste_2020-10-22_15-11-11.png)
[http://cdn.note.manoner.com/Snipaste_2020-10-22_15-11-28.png](http://cdn.note.manoner.com/Snipaste_2020-10-22_15-11-28.png)

**Environment (please complete the following information):**
 - OS: [Mac OS 10.15.7]
 - Go Version: [1.14.2]

**Additional context**

**Comment by myzhan** [comment]
1. 目前 StableRateLimiter 用的令牌桶，每秒填充一次，不是平滑的。刚刚填充完，所有 block 住的 task 都恢复执行，这个应该是 CPU 暴涨的原因。如果令牌桶被消耗完，所有 task 都被 block 住，这个时候 CPU 消耗很低。
2. 你限制了 200RPS，并发数给了 10000，这个比例不正常。

**Comment by Manoner** [comment]
> 1. 目前 StableRateLimiter 用的令牌桶，每秒填充一次，不是平滑的。刚刚填充完，所有 block 住的 task 都恢复执行，这个应该是 CPU 暴涨的原因。如果令牌桶被消耗完，所有 task 都被 block 住，这个时候 CPU 消耗很低。
> 2. 你限制了 200RPS，并发数给了 10000，这个比例不正常。

谢谢！

一般 RPS 值和并发数的 比例 是多少？

**Comment by Manoner** [comment]
经过多次验证发现，运行一段时间后，比如会出现CPU暴涨的情况。
例如：
并发设置为10000 Users，RPS 也设置为10000 
执行一定时间后，必然会出现CPU暴涨的情况。

**备注：**
其实并发用户数和RPS同时设置为2000，也会遇到CPU暴涨的情况，需要多试几次，或者多运行一段时间，必然会重现。

猜测原因会不会是因为：
**先关掉 broadcastChannel ，再初始化 broadcastChannel 地址后，是否并发安全？？会不会存在向旧的chanel地址取值的情形？**

```go
// Start to refill the bucket periodically.
func (limiter *StableRateLimiter) Start() {
	limiter.quitChannel = make(chan bool)
	quitChannel := limiter.quitChannel
	go func() {
		for {
			select {
			case <-quitChannel:
				return
			default:
				atomic.StoreInt64(&limiter.currentThreshold, limiter.threshold)
				time.Sleep(limiter.refillPeriod)
				close(limiter.broadcastChannel)  // 先关掉  broadcastChannel
				limiter.broadcastChannel = make(chan bool)  // 重新初始化 broadcastChannel，获取内存地址
			}
		}
	}()
}

// Acquire a token from the bucket, returns true if the bucket is exhausted.
func (limiter *StableRateLimiter) Acquire() (blocked bool) {
	permit := atomic.AddInt64(&limiter.currentThreshold, -1)
	if permit < 0 {
		blocked = true
		// block until the bucket is refilled
                 //  先关掉 broadcastChannel ，再初始化 broadcastChannel 地址后，是否并发安全？？会不会存在向旧的chanel地址取值的情形？
		<-limiter.broadcastChannel 
	} else {
		blocked = false
	}
	return blocked
}
```

**Comment by Manoner** [comment]
临时测试见下，并发用户数量 ：10000， RPS ：200，执行临时测试修改后，CPU使用率稳定，见下图。

```go
// Start to refill the bucket periodically.
func (limiter *StableRateLimiter) Start() {
	limiter.quitChannel = make(chan bool)
	limiter.broadcastChannel = make(chan bool, 100000) // 临时开辟一个10w的channel大小
	quitChannel := limiter.quitChannel
	go func() {
		for {
			select {
			case <-quitChannel:
				return
			default:
        // 向 channel 中放入200个，在休眠 1 秒，达到并发速率的限制
				for i := 0; i < 200; i++ {
					limiter.broadcastChannel <- true
				}
        // 休眠 1 秒
				time.Sleep(1 * time.Second)
			}
		}
	}()
}

// Acquire a token from the bucket, returns true if the bucket is exhausted.
func (limiter *StableRateLimiter) Acquire() (blocked bool) {
	<-limiter.broadcastChannel
	return false
}
```

执行结果，如图所示：
![Snipaste_2020-10-23_11-55-26](https://user-images.githubusercontent.com/60100619/96954784-b4220100-1526-11eb-964e-de750e15a4be.png)

[http://cdn.note.manoner.com/Snipaste_2020-10-23_11-55-26.png](http://cdn.note.manoner.com/Snipaste_2020-10-23_11-55-26.png)

**Comment by myzhan** [comment]
截图里面没有 CPU 的使用情况。你测试用的 Task 部分代码可以贴出来看看吗？

**Comment by myzhan** [comment]
或者跑一段时间的 pprof，看看结果。

**Comment by Manoner** [comment]
> 或者跑一段时间的 pprof，看看结果。

我先关闭下这个问题，等我再验证下。有问题再和你沟通。
