### ISSUE TITLE
是否考虑给boomer 做版本管理

### ISSUE THREAD

**Issue by dovefi** [myzhan/boomer#104]
boomer 当前没有release， 也没有tags, 适配locust的时候比较难搞

**Comment by myzhan** [comment]
因为 locust 经常修改协议导致不兼容，boomer 目前只保证支持最新版本的 locust。如果 boomer 加上版本的话，后续可能要维护一个不同版本适配的不同 locust 版本列表。如果这块有好主意的话，不妨详细说说。

**Comment by myzhan** [comment]
启用 tag 版本，用 go module 的话比较方便。master 分支只支持 locust 的 master 版本了，如果要用旧版本，可以切换到对应的 tag。
