### ISSUE TITLE
上报的数据导致locust计算错误率异常

### ISSUE THREAD

**Issue by solxnp** [myzhan/boomer#106]
![image](https://user-images.githubusercontent.com/18416053/98674386-b04e0580-2393-11eb-9514-fdd7bb9a7189.png)

boomer及locust均使用最新版本

最小案例：

> task使用 /examples/http/client.go，只将 url 值改为了 http://www.baidu.com/s?wd=python

**Comment by myzhan** [comment]
这是 locust 的 BUG，目前错误率的计算公式是失败数除以请求数，但是它没有把失败算在请求总数里面，会有失败数大于请求数的情况。
