### ISSUE TITLE
标记一条请求为失败的时候，没有将statsEntry.numRequests + 1

### ISSUE THREAD

**Issue by solxnp** [myzhan/boomer#107]
locust将numRequests 记为已请求的所有次数，但boomer当前在标记请求失败时，只调用了s.total.logError方法，并没有去调用s.total.log方法，这会导致当请求失败次数大于成功次数时，计算出来的失败率会超过100%

**Comment by solxnp** [comment]
如 #106

**Comment by solxnp** [comment]
在看locust的源码中看到他们是在请求失败后也会通过调用请求成功的函数来使num_requests + 1

` 

        def on_request_success(request_type, name, response_time, response_length, **kwargs):
            self.stats.log_request(request_type, name, response_time, response_length)

        def on_request_failure(request_type, name, response_time, response_length, exception, **kwargs):
            self.stats.log_request(request_type, name, response_time, response_length)
            self.stats.log_error(request_type, name, exception)`

**Comment by solxnp** [comment]
我尝试修改之后解决了这个问题，但发现另外一个问题：在短时间内大量报错的时候，计算出来的TPS会失真
![image](https://user-images.githubusercontent.com/18416053/98937074-dc4ac180-2520-11eb-9c7a-019a898b0333.png)

**Comment by solxnp** [comment]
已改好  确认下这是否是个Bug
![image](https://user-images.githubusercontent.com/18416053/98940595-2da97f80-2526-11eb-8f5e-8b91f2b74ef6.png)

**Comment by myzhan** [comment]
OK，应该是个 BUG。locust 以前是这样计算的 https://github.com/locustio/locust/blob/v0.7.5/locust/stats.py#L190，现在这样计算 https://github.com/locustio/locust/blob/master/locust/stats.py#L341。

如果修好了，麻烦提一个 PR 吧~
