### ISSUE TITLE
Locust统计Requests比实际的少

### ISSUE THREAD

**Issue by lihuacai168** [myzhan/boomer#109]
# Describe the bug
使用Boomer做mqtt压测，Locust统计的请求数，比实际发出去的消息条数要

- 我自己统计发出去数量：228
![image](https://user-images.githubusercontent.com/11568297/100051450-e640be80-2e56-11eb-95c2-4102ae5e1b7b.png)
- MQTT客户端订阅的条数也是：228
![image](https://user-images.githubusercontent.com/11568297/100051501-03758d00-2e57-11eb-8269-dd2b9ac00f04.png)

- Locust统计：116
![image](https://user-images.githubusercontent.com/11568297/100051542-1ab47a80-2e57-11eb-8f07-d2b553860cf8.png)

不知道是不是点击了Stop之后，Boomer就停止上报请求数量，但实际上task还在运行导致的。
# 复现步骤
- 正常开始压测
- 在Locust的web页面右上角点击Stop

# Environment (please complete the following information)
 - OS: macOS 10.15.7
 - Go Version: 1.14.4 darwin/amd64
 - Locust Version：1.4.1
 - Boomer Version：github.com/myzhan/boomer v0.0.0-20201113075110-e17d364d020f（最新版）

**Comment by myzhan** [comment]
停止压测后，deviceTime 这行日志还打印吗？另外如果并发大于 1，你用 j++ 统计不是线程安全的。

**Comment by lihuacai168** [comment]
> 停止压测后，deviceTime 这行日志还打印吗？另外如果并发大于 1，你用 j++ 统计不是线程安全的。

停止压测之后，deviceTime这行日志不会继续打印了。
j++是线程不安全的，在不安全的情况下，j的值是比线程安全的时候要小，但实际结果Requests比j还小。
我加了锁，还是一样的结果。
![image](https://user-images.githubusercontent.com/11568297/100075333-ca4f1400-2e7a-11eb-8819-5defc3216251.png)

**Comment by myzhan** [comment]
因为看不到你的 task 是怎么写的，你可以在这个位置加个日志，看看上报给 master 的数据是怎样的。

https://github.com/myzhan/boomer/blob/e17d364d020f6feae49a06c05f02b19c6dcc6a5e/stats.go#L148

**Comment by lihuacai168** [comment]
> 因为看不到你的 task 是怎么写的，你可以在这个位置加个日志，看看上报给 master 的数据是怎样的。
> 
> https://github.com/myzhan/boomer/blob/e17d364d020f6feae49a06c05f02b19c6dcc6a5e/stats.go#L148


这个是在你说的位置加了日志，我把整个data输出
![image](https://user-images.githubusercontent.com/11568297/100098735-6b4cc780-2e99-11eb-8285-745053985bc2.png)
消息上报的我直接用了例子sample里面提供的
`			boomer.RecordSuccess("tcp", "sendMsg", elapsed.Nanoseconds()/int64(time.Millisecond), int64(10))
`
在locust的web端点击了停止，这个消息还是会继续上报，等上报两条后，我ctrl+c终止了boomer程序。
这次我统计的请求次数是372，locust统计的是121
![image](https://user-images.githubusercontent.com/11568297/100098860-959e8500-2e99-11eb-905f-6d31d46cb8cd.png)


```
deviceTime: 1606223193, success msg index: 372 elapsed: 15.054208ms  
2020/11/24 21:06:45 map[errors:map[] stats:[map[last_request_timestamp:1606223204 max_response_time:28 method:tcp min_response_time:13 name:sendMsg num_fail_per_sec:map[] num_failures:0 num_none_requests:0 num_reqs_per_sec:map[1606223202:7 1606223203:134 1606223204:110] num_requests:251 response_times:map[13:15 14:60 15:171 16:2 25:2 28:1] start_time:1606223202 total_content_length:2510 total_response_time:3710]] stats_total:map[last_request_timestamp:1606223204 max_response_time:28 method: min_response_time:13 name:Total num_fail_per_sec:map[] num_failures:0 num_none_requests:0 num_reqs_per_sec:map[1606223202:7 1606223203:134 1606223204:110] num_requests:251 response_times:map[13:15 14:60 15:171 16:2 25:2 28:1] start_time:1606223202 total_content_length:2510 total_response_time:3710]]
2020/11/24 21:06:48 map[errors:map[] stats:[] stats_total:map[last_request_timestamp:1606223205 max_response_time:0 method: min_response_time:0 name:Total num_fail_per_sec:map[] num_failures:0 num_none_requests:0 num_reqs_per_sec:map[] num_requests:0 response_times:map[] start_time:1606223205 total_content_length:0 total_response_time:0]]
2020/11/24 21:06:51 map[errors:map[] stats:[] stats_total:map[last_request_timestamp:1606223208 max_response_time:0 method: min_response_time:0 name:Total num_fail_per_sec:map[] num_failures:0 num_none_requests:0 num_reqs_per_sec:map[] num_requests:0 response_times:map[] start_time:1606223208 total_content_length:0 total_response_time:0]]
^C2020/11/24 21:06:52 shut down

```

**Comment by myzhan** [comment]
看起来像是你压测端的系统时间，和 locust 端的系统时间有差异，可以确认一下这个点。

**Comment by lihuacai168** [comment]
> 看起来像是你压测端的系统时间，和 locust 端的系统时间有差异，可以确认一下这个点。

deviceTime目前我写死的，用了刚开始发送压测的时间。
locust接收到的是当前时间戳。
所以locust收到的时间会比deviceTime大一点。

**Comment by myzhan** [comment]
从你打印出来的日志来看，boomer 定时统计到的 RPS，有给 locust 上报到 num_requests: 251 了，所以统计这块应该没问题，可以去看看 locust 的收集逻辑。我之前遇到过的一个场景，就是 locust 和 boomer 两台机器上的系统时间有差异，locust 会忽略掉一些数据。

**Comment by lihuacai168** [comment]
> 从你打印出来的日志来看，boomer 定时统计到的 RPS，有给 locust 上报到 num_requests: 251 了，所以统计这块应该没问题，可以去看看 locust 的收集逻辑。我之前遇到过的一个场景，就是 locust 和 boomer 两台机器上的系统时间有差异，locust 会忽略掉一些数据。

locust和boomer我都是在本机部署，所以时间应该是相同的。

**Comment by myzhan** [comment]
有点诡异，可能要你结合 locust 的 stat 这块看看了

**Comment by FlyLoveFly** [comment]
修复上述bug：
Events模块，新增属性STATE_LOCUST = "init"
![image](https://user-images.githubusercontent.com/90945272/133870088-9bfe8dcd-fb0f-4229-bef7-123f0fd32d33.png)
Runners模块，修改如下代码，新增events.STATE_LOCUST = 'stop'，并注释 
![image](https://user-images.githubusercontent.com/90945272/133870095-8e1a072f-98de-4f92-9668-a265a3d700cb.png)
Core.py模块，修改如下
events.STATE_LOCUST='running'
![image](https://user-images.githubusercontent.com/90945272/133870101-39994aff-7e47-432c-92e2-6451ca93ec83.png)

**Comment by leididi** [comment]
locust 2.15.1
boomer v1.6.1-0.20230321111411-41a131e3afc4
Go Version 1.19
macos 13

相同的问题。怎么解决呢
