### ISSUE TITLE
can't install,issue "package github.com/myzhan/boomer.git: invalid version control suffix in github.com/ path"

### ISSUE THREAD

**Issue by acejqzhang** [myzhan/boomer#11]
can't install

**Comment by acejqzhang** [comment]
issue below:
go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/myzhan/boomer: exec: "git": executable file not found in $PATH

**Comment by myzhan** [comment]
This is not a issue of boomer.

Just install git and put it in your $PATH, so "go get" command can use it to install packages.

**Comment by acejqzhang** [comment]
thank you very much for replying
what my linux install git has some problems, so do you have other way to install boomer?thanks

**Comment by myzhan** [comment]
You can manually put all the packages in $GOPATH.

But I think it's easier for you to use git. let "go get" to do all the dirty works.

**Comment by nanjizhilian** [comment]
执行go build -tags 'goczmq' main.go报错# github.com/myzhan/boomer
../../../../pkg/mod/github.com/myzhan/boomer@v1.6.0/client_czmq.go:43:8: dealer.SetOption undefined (type *goczmq.Sock has no field or method SetOption)
../../../../pkg/mod/github.com/myzhan/boomer@v1.6.0/client_czmq.go:43:19: undefined: goczmq.SockSetIdentity

**Comment by myzhan** [comment]
@nanjizhilian 参考 https://github.com/myzhan/boomer/issues/119
