### ISSUE TITLE
使用boomer进行压测时，出现资源竞争问题

### ISSUE THREAD

**Issue by chenzheng123** [myzhan/boomer#111]
**Describe the bug**
当进行并发压测的时候出现资源竞争问题。

**To Reproduce**
1.先启动locust master端，再启动boomer slave端，命令为 go run -race main.go 并发=100，spawn rate=50进行压测；
2.压测过程终端打印DATA RACE（资源竞争）

**Expected behavior**
终端正常输出，不打印DATA RACE

**Screenshots**
https://github.com/chenzheng123/edata/blob/master/%E8%B5%84%E6%BA%90%E7%AB%9E%E4%BA%891.png
https://github.com/chenzheng123/edata/blob/master/%E8%B5%84%E6%BA%90%E7%AB%9E%E4%BA%892.png
https://github.com/chenzheng123/edata/blob/master/%E8%B5%84%E6%BA%90%E7%AB%9E%E4%BA%893.png

**Environment (please complete the following information):**
 - OS: MAC OS 10.15.5
 - Go Version: go1.15.5 darwin/amd64

**Additional context**

**Comment by myzhan** [comment]
嗯，确实。不过目前临界区较小，如果有 race condition 也不会导致问题。可以提个 PR 改一下。

**Comment by chenzheng123** [comment]
观察到r.state和r.numClients出现了竞争，可以使用sync.Mutex 加锁解决吗？

**Comment by myzhan** [comment]
r.state 我感觉影响不大。r.numClients 应该用 atomic load 就行了。

**Comment by chenzheng123** [comment]
修改了numClients和state的读取和写入方式后，发现其他地方也出现了data race
