### ISSUE TITLE
boomer是否可以支持分布式部署？

### ISSUE THREAD

**Issue by chenzheng123** [myzhan/boomer#112]
是否可以让boomer支持分布式部署呢？

**Comment by myzhan** [comment]
可以的呀，现在就支持，多个 boomer 连一个 locust

**Comment by chenzheng123** [comment]
但是我实际压测发现，多个boomer连接一个locust，发现并发并没有增加，是不是因为都连接到同一个端口5557了？

**Comment by myzhan** [comment]
并发数是 locust 下发的，会平均分给多个 boomer 实例。如果你要并发数增加，master 启动测试的时候也要调整。

**Comment by chenzheng123** [comment]
实际情况是：我设置的并发数是10000，2个boomer，代码中rateLimiter设置为3000/s，但均分后总的rps并不能到达3000。

**Comment by myzhan** [comment]
并发数和 RPS 不是强关联的，如果并发数上来了，RPS 没上去，一要看压测逻辑有没有问题，二要看被压端有没有问题。另外 rateLimiter 自身有等待的影响，如果不能达到 3000，但刚好达到29xx 左右，你可以稍微把 rateLimiter 调的比 3000 高一点，如果差很多，那就不是 rateLimter 的问题了。
