### ISSUE TITLE
压测一会后接受到master 的stop

### ISSUE THREAD

**Issue by chenzheng123** [myzhan/boomer#115]
压测一会后slave接受到master的stop消息：

图示如下：
https://github.com/chenzheng123/edata/blob/master/%E6%8E%A5%E5%8F%97master-stop.png

**Comment by myzhan** [comment]
可以试着升级一下 boomer 版本，兼容 master 连续发两次 stop 消息过来的情况。

**Comment by chenzheng123** [comment]
1. 升级后gomq/zmtp报错如下，无法连接到master：
19:18:17 gomq.go:199: gomq/zmtp: Got error while receiving greeting: Version 3.0 received does match expected version 3.1
19:18:17 runner.go:426: Failed to connect to master(0.0.0.0:5557) with error gomq/zmtp: Got error while receiving greeting: Version 3.0 received does match expected version 3.1
2. 发现是zmtp/conn 下面代码导致的：
  if greeting.Version != version {
		  return fmt.Errorf("Version %v.%v received does match expected version %v.%v", int(greeting.Version[0]), int(greeting.Version[1]), int(majorVersion), int(minorVersion))
	  }
修改version常量即可。

**Comment by myzhan** [comment]
对，上游 gomq 不知道为啥把版本号改了，你可以参考前面的 issue
