### ISSUE TITLE
Standalone模式实际的Clients和spawnRate 没有起到限制每秒的数量

### ISSUE THREAD

**Issue by Audyzj** [myzhan/boomer#117]
**Describe the bug**

**To Reproduce**

`func main() {
	log.SetFlags(log.LstdFlags | log.Lshortfile)

	task1 := &boomer.Task{
		Name:   "foo",
		Weight: 10,
		Fn:     foo,
	}

	numClients := 10
	spawnRate := 10.0
	globalBoomer = boomer.NewStandaloneBoomer(numClients, spawnRate)
	globalBoomer.Run(task1)`

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. centos]
 - Go Version: [e.g. 1.10]

**Additional context**
![1614682711(1)](https://user-images.githubusercontent.com/19618671/109638730-51520d80-7b89-11eb-8cfb-5c508b3cdc5c.png)
请问我想在standalone模式下设置每秒的挂载量和总挂载量需要怎么配置呢？比如一共压1000人，每秒压100人，这样？

**Comment by myzhan** [comment]
numClients 填 1000，spawnRate 填 100.0

**Comment by Audyzj** [comment]
![1614738836(1)](https://user-images.githubusercontent.com/19618671/109743641-fe6d6a00-7c0b-11eb-8399-14aebccf6c6c.png)
我看了一下spawnWorkers的源码，这边好像是会阻塞式的一直调用，除非有rateLimit

**Comment by Audyzj** [comment]
![1614738836(1)](https://user-images.githubusercontent.com/19618671/109747799-c158a600-7c12-11eb-97a9-0eaddb044de6.png)
我就是在sstandalone.go的demo上尝试的，只限制numClients ，spawnRate其实只是限制的器的协程数，可是每个协程可能还是会反复的调用 task,短连接可能会1秒内多次请求，不过这样设计也是对的！

**Comment by myzhan** [comment]
别搞混了，numClients 和 spawnRate 控制的是并发数，也就是协程数。你上面说的压多少人，我理解是并发数，不是请求数。rateLimit 控制的是每秒请求（RPS）峰值。只限并发，不限 RPS，那就是压测端和被压端能跑多快就跑多快。

**Comment by Audyzj** [comment]
嗯嗯，谢谢哈

**Comment by 91Eric** [comment]
@myzhan  你好，这里是否可以这样理解：numClients 和 spawnRate 控制的是最多多少个协程数以及在没达到numClients之前每秒增加的数量，而rateLimit 控制的是每秒所有协程可以请求的峰值，实际是否能跑到这个峰值要看本身压测机器和服务器的性能，也有可能本身性能超过rateLimit 设置的数量，但是由于这里做了限制，因此最多也就只能达到rateLimit所设置的数量，如果使用默认的不设置rateLimit的情况下，就是本身机器能跑多少算多少？
![image](https://user-images.githubusercontent.com/16057575/180679126-501790e1-23a4-40f7-bac3-02daff5a66d6.png)

**Comment by myzhan** [comment]
@91Eric 默认情况是你理解的这样。不过 rateLimiter 其实是一个 interface，你可以自定义实现更精细的请求控制。

**Comment by 91Eric** [comment]
好的，多谢，我再看下这部分的代码

**Comment by 91Eric** [comment]
这里还有几个问题想咨询下，我阅读了此部分代码后，结合本地测试，当我是用locust页面设置了peak concurrency 用户，此时locust会从0开始根据Spawn rate 设定的数值依次发送给bommer，按照这部分代码的逻辑，会创建spawnCount 数量的协程进行压测，如果最后一次传输的数值达到peak concurrency数值后，创建peak concurrency数量的协程后，不会在继续执行压测，这样岂不是无法在某个压测值上做持续压测？我尝试在实际业务代码中通过创建协程的方式增大并发，但是发现此时协程会呈现爆炸式的增长，即使我将peak concurrency 设置为2，这也使我很疑惑

**Comment by 91Eric** [comment]
@myzhan 这里还有几个问题想请教下，
1、我阅读了此部分代码后，结合本地测试，当我是在locust页面设置了peak concurrency 用户数，此时locust会从0开始根据Spawn rate 设定的数值依次发送给bommer（对应值存储在变量 spawnCount），按照这部分代码的逻辑，会创建 spawnCount 数量的协程进行压测，
如果最后一次传输的数值达到peak concurrency数值后，创建peak concurrency数量的协程后，不会在继续执行压测，这样岂不是无法在某个压测值上做持续压测？我尝试在实际业务代码中通过创建协程的方式增大并发，但是发现此时协程会呈现爆炸式的增长，
即使我将peak concurrency 设置为2，这也使我很疑惑，
2、既然此处是通过for循环，创建spawnCount 的协程数，假如1秒内可以创建完成，但是此时实际的并发数也并不是spawnCount对应的值，应该是要取决于 业务代码中的逻辑以及实际有多少协程在运行，后者取决于测试机器的性能以及服务器的性能？刚开始我简单的以为
spawnCount 数量就是并发数量，但是实际操作后发现貌似并不是这样
还需要麻烦解答一下上面的疑惑，多谢

**Comment by myzhan** [comment]
> 创建peak concurrency数量的协程后，不会在继续执行压测
理论上不会这样，能重现吗？应该是会停留在最终的并发数上继续跑 task。

> 我尝试在实际业务代码中通过创建协程的方式增大并发
不能这样用，并发的控制要留给 locust 来控制。

> spawnCount 数量就是并发数量，但是实际操作后发现貌似并不是这样
你上面已经看到，locust会从0开始根据Spawn rate 设定的数值依次发送给bommer。boomer 在每次收到指令后，会先停止上一次创建的协程，再新建spawnCount对应数量的协程。runner 这块的代码不多，你仔细看看。

**Comment by zzjcfj** [comment]
@myzhan 有个问题请教下，有多个worker 时，程序如何知道locust为每个worker分配的id?

**Comment by 91Eric** [comment]
您好，您的来信我已收到.

**Comment by myzhan** [comment]
@zzjcfj 你说的是 nodeId？如果是这个的话，它不是 locust 分配的，是 worker 自己生成的一个 uuid。

**Comment by zzjcfj** [comment]
@myzhan  谢谢！明白了worker 的id是uuid。那(index 3)是不是locust分配的?会给到worker吗？ 下面是locust 的输出：
[2023-05-04 01:45:49,649] boomer/INFO/locust.runners: Worker 'boomer_3795d296fd0c42f4962b2f39e0774021' (index 3) quit. 0 workers ready.
[2023-05-04 10:03:01,407] boomer/INFO/locust.runners: Worker 'boomer_291e0b3eed4b4059ac681b590da889cc' (index 2) quit. 0 workers ready.

**Comment by myzhan** [comment]
@zzjcfj 理论上可以获取到，但是 boomer 没有开放这个，你目前是什么需求需要用到？

**Comment by zzjcfj** [comment]
@myzhan MQTT压测时，clientid 要求是不重复的。希望用不同的worker id+顺序号来表示 MQTT 的 clientid

**Comment by zzjcfj** [comment]
@myzhan 因mqtt clientid不能超过23个字符，看样子可以取uuid左边的hostname作为clientid的一部分，但在同一台主机上运行多个worker还是不好办。

**Comment by myzhan** [comment]
@zzjcfj 如果只是为了不重复，你可以直接给每个 client 分配一个 uuid？不太理解为啥要跟 worker index 关联。
