### ISSUE TITLE
locust --master -f prometheus_exporter.py为什么界面没变化？

### ISSUE THREAD

**Issue by ankisme** [myzhan/boomer#118]
我想用`locust --master -f prometheus_exporter.py`看看新的界面，但是打开的界面跟`locust --master -f dummy.py`的一模一样，好像没变化

是不是我的用法有问题？我执行命令后，用`0.0.0.0:8089`和`127.0.0.1:8089`这2个地址打不开locust界面，但是用`localhost:8089`能打得开locust界面（我在`C:\Windows\System32\drivers\etc\hosts`里加了一行`127.0.0.1 localhost`）

**Comment by myzhan** [comment]
你对这个东西的用法理解错误，你需要先去熟悉 prometheus 和 grafana。
