### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by mudaixiansheng** [myzhan/boomer#120]
The scene of the panic caused by a specific scenario is as follows:
1.start master and slave.
2.Spawning 100 clients at the rate 1 clients/s...     
3.click stop before clients less than 100.
4.click new test, repeat 2...
5.slave panic

The following is the stack：
2021/04/15 06:02:43 Spawning 100 clients at the rate 1 clients/s...
2021/04/15 06:02:46 Recv stop message from master, all the goroutines are stopped
panic: close of closed channel

goroutine 37 [running]:
github.com/myzhan/boomer.(*runner).stop(0xc000308000)
     /armyant/vendor/github.com/myzhan/boomer/runner.go:218 +0x71
github.com/myzhan/boomer.(*slaveRunner).onMessage(0xc000308000, 0xc000137a10)
     /armyant/vendor/github.com/myzhan/boomer/runner.go:378 +0x587
github.com/myzhan/boomer.(*slaveRunner).startListener.func1(0xc000308000)
     /armyant/vendor/github.com/myzhan/boomer/runner.go:410 +0x4c
created by github.com/myzhan/boomer.(*slaveRunner).startListener
     /armyant/vendor/github.com/myzhan/boomer/runner.go:406 +0x3f

**Comment by myzhan** [comment]
Fixed
