### ISSUE TITLE
boomer统计的响应时间不准确

### ISSUE THREAD

**Issue by delav** [myzhan/boomer#122]
**Describe the bug**
做http接口压测使用Boomer作slave统计的响应时间，比使用locust作slave统计的响应时间相差几百倍

这是boomer作slave的统计结果：
![企业微信截图_16207882328241](https://user-images.githubusercontent.com/19924413/117912798-bad16380-b312-11eb-8c75-dfe277a3b286.png)

这是locust本身作slave的统计结果：
![NMK(9CAV`1T9AHM51`94IFF](https://user-images.githubusercontent.com/19924413/117912838-cde43380-b312-11eb-895d-283dc2459526.png)

master和slave都是在同一台机器上执行的。

**Environment (please complete the following information):**
 - OS: centos
 - Go Version: go version go1.16.3 linux/amd64
 - Locust Version：1.5.1
 - Boomer Version：boomer@v0.0.0-20210122030331-a9eddc3e0219

**Comment by myzhan** [comment]
现在接口调用耗时，是你自行获取的，时候搞错了时间单位？

**Comment by delav** [comment]
> 现在接口调用耗时，是你自行获取的，是否搞错了时间单位？

这样啊，我再看看，谢谢
