### ISSUE TITLE
Version 3.1 received does match expected version 3.0

### ISSUE THREAD

**Issue by walterray** [myzhan/boomer#123]
2021/06/21 16:26:34 Failed to connect to master with error gomq/zmtp: Got error while receiving greeting: Version 3.1 received does match expected version 3.0
2021/06/21 16:26:56 Timeout waiting for sending quit message to master, boomer will quit any way.

I have checked protocol version on my MacBook in file gomq/zmtp/protocol.go, it indicates:
    ...
    const (
            majorVersion uint8 = 3
            minorVersion uint8 = 0
    )
    ...

**Comment by myzhan** [comment]
Which version of locust are you using?

**Comment by walterray** [comment]
locust 1.1.1
python3.7.3

**Comment by myzhan** [comment]
You can try to upgrade locust to the lastest version.

**Comment by walterray** [comment]
> You can try to upgrade locust to the lastest version.

@myzhan I have tried it with locust 1.5.3, but still got same error.

**Comment by myzhan** [comment]
Did you modify the source code of gomq? Or you can change minorVersion to 1 to get rid of this issue.

**Comment by walterray** [comment]
> minorVersion to 1 to get rid of this issue.
@myzhan No, I never modify gomq. I'll try to change minorVersion to 1 in file zmtp/protocol.go

**Comment by walterray** [comment]
> Did you modify the source code of gomq? Or you can change minorVersion to 1 to get rid of this issue.

@myzhan I tried it again after changing minorVersion to 1, but this issue still occurred.

**Comment by myzhan** [comment]
The log is printed at conn.go, check the code of gomq and make sure you modification takes effect.

**Comment by walterray** [comment]
> The log is printed at conn.go, check the code of gomq and make sure you modification takes effect.

@myzhan I modified the minorVersion to 1 and then executed "go build -o a.out main.go", but it did not take effect and the minorVersion value was still 0.

**Comment by myzhan** [comment]
Sorry these is nothing I can do. You may try to find out why the modification doesn't take effect.

**Comment by walterray** [comment]
> Sorry these is nothing I can do. You may try to find out why the modification doesn't take effect.

@myzhan Really appreciate your nice support. now it works well after versions upgrade of locust and go modules. 
locust: 1.5.3

go modules as below:
...
require (
	github.com/StackExchange/wmi v0.0.0-20190523213315-cbe66965904d // indirect
	github.com/asaskevich/EventBus v0.0.0-20200907212545-49d423059eef // indirect
	github.com/go-ole/go-ole v1.2.4 // indirect
	github.com/google/uuid v1.1.2 // indirect
	github.com/myzhan/boomer v0.0.0-20201113075110-e17d364d020f
	github.com/olekukonko/tablewriter v0.0.4 // indirect
	github.com/shirou/gopsutil v3.20.10+incompatible // indirect
	github.com/stretchr/testify v1.6.1 // indirect
	github.com/ugorji/go v1.2.0 // indirect
	github.com/zeromq/goczmq v4.1.0+incompatible // indirect
	github.com/zeromq/gomq v0.0.0-20201031135124-cef4e507bb8e // indirect
	github.com/zeromq/gomq/zmtp v0.0.0-20201031135124-cef4e507bb8e // indirect
	golang.org/x/sys v0.0.0-20201117222635-ba5294a509c7 // indirect
)
...
