### ISSUE TITLE
some requirements ……

### ISSUE THREAD

**Issue by mudaixiansheng** [myzhan/boomer#124]
**Describe somes demand**
1、I want to use boomer like below：

	task := &boomer.Task{
		Name:   "busWork",
		Weight: 10,
		Fn:     busWork,
	}

	ratelimiter := boomer.NewStableRateLimiter(100, time.Second)
	
	switch *mode {
	case common.Once:
		busWork()
	case common.Standalone:
		nc := int(*numClient)
		var sr float64
		if *spawnRate == -1 {
			sr = float64(nc)
		} else {
			sr = float64(*spawnRate)
		}
		globalBoomer = boomer.NewStandaloneBoomer(nc, sr)
		globalBoomer.SetRateLimiter(ratelimiter)
		globalBoomer.Run(task)
	case common.DistributedMode:
		globalBoomer = boomer.NewBoomer(&masterHost, &masterPort)
		globalBoomer.SetRateLimiter(ratelimiter)
		globalBoomer.Run(task)
	}

**Expected behavior**
1. globalBoomer = boomer.NewBoomer(&masterHost, &masterPort)

Whether masterHost&masterPort can be set to as global variables, also they can be referenced by the script.

2. In standalone mode， whether to consider adding final statistics as a extra output option during performance testing?

**Comment by myzhan** [comment]
1. Boomer should be used as a library, so I'm trying to avoid global variables. You can define host and port by youself, and use them in the script.
2. You can use AddOutput() to add custom output destination.
