### ISSUE TITLE
Support locust version 2

### ISSUE THREAD

**Issue by joshcarp** [myzhan/boomer#126]
**Describe the bug**
Using locust version 1.6 yields the following errors:
```
/ERROR/locust.runners: An old (pre 2.0) worker tried to connect (foobar-d92tf_95b79873e7684c3980d36658b19e54ee). That's not going to work.
```

**To Reproduce**
1. Startup locust 2 as a master
2. Connect with boomer

**Expected behavior**
Newer locust versions should exist

**Screenshots**

**Environment (please complete the following information):**
 - OS: debian
 - Go Version: 1.16

**Comment by myzhan** [comment]
Hi @joshcarp, are you willing to submmit a MR for this?

**Comment by myzhan** [comment]
Working on this issue, I think it's time to versionize boomer and drop support for every version of locust in the master branch.

**Comment by Slach** [comment]
@myzhan thanks a lot for your efforts, `locust` + `boomer` is a great combo

**Comment by myzhan** [comment]
Now the master branch supports locust 2 and drops support for locust 1, please give it a try.

**Comment by joshcarp** [comment]
Hey thanks heaps for the quick response on this

**Comment by 53652864** [comment]
> @53652864 you should update boomer first.

[2021-08-31 14:44:50,965] will-nb/ERROR/locust.runners: An old (pre 2.0) worker tried to connect (will-nb_b32b58c4468b409880af31264d9913c9). That's not going to work.

**Comment by myzhan** [comment]
Of course it's not going to work, have you updated boomer?

**Comment by wangtao2213405054** [comment]
why go get github.com/myzhan/boomer It pull to version 1.6.0

**Comment by nansuri** [comment]
hi I'm also experienced this, when do "go get github.com/myzhan/boomer" it always pull version 1.6.0 which not compatible with the locust 2.0

**Comment by myzhan** [comment]
@nansuri Maybe you have pulled boomer before? Try to run "go get -U github.com/myzhan/boomer"

**Comment by cwhight** [comment]
I am also unable to pull a more recent version than 1.6.0 - cannot run with a new version locust
