### ISSUE TITLE
能否改为在代码中控制是否使用goczmq？

### ISSUE THREAD

**Issue by ankisme** [myzhan/boomer#128]
```
go build -tags 'goczmq' your-code.go
```
现在是通过build -tags来决定是否采用goczmq，如果是多人协作，应该如何保证每个人默认就开启了goczmq呢？是否有相应的方案？

如果是在代码中控制是否采用goczmq，代码库肯定是一样的，就没有协作方面的问题，就不会出现这类现象，即人员1开启了goczmq，人员2没开启goczmq，结果人员2使用时出现问题，人员1过去一看，发现没开启goczmq，说你开启goczmq再试一试，这类事情的沟通成本是非常高的

可能通过tag控制是想节省编译时间和编译出的包大小，但我看go.mod中同样引入了`github.com/zeromq/goczmq v4.1.0+incompatible // indirect`这条配置项，所以感觉并没有省什么资源

**Comment by myzhan** [comment]
这类问题，应该在打包脚本里面统一。目前通过 tags 控制，是因为 goczmq 的依赖安装较麻烦，改为可选依赖，即没有 goczmq，也可以编译通过。
