### ISSUE TITLE
The master version fails to compile with goczmq

### ISSUE THREAD

**Issue by zhaozhiquan** [myzhan/boomer#129]
**Describe the bug**
The master version fails to compile with goczmq

**To Reproduce**
1. go build -tags "goczmq" -o test test.go

**Expected behavior**
Compiled successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/25030068/129301649-bfff2480-a397-4ae5-91c7-b60a227a4197.png)

**Environment (please complete the following information):**
 - OS: 18.04.1-Ubuntu
 - Go Version: go1.14

**Additional context**
github.com/myzhan/boomer v1.6.1-0.20210809102744-c8687f7c951b // indirect
github.com/zeromq/goczmq v4.1.0+incompatible // indirect

**Comment by myzhan** [comment]
See also https://github.com/myzhan/boomer/issues/119

**Comment by zhaozhiquan** [comment]
github.com/zeromq/goczmq 没有4.2的版本可安装，另外，直接clone goczmq 的master分支，同样会编译失败。
还是先使用boomer 1.6吧。话说，现在gomq稳定了吗？

**Comment by myzhan** [comment]
就是这个，https://github.com/zeromq/goczmq/tree/v4.2.0。gomq 不怎么维护了，如果有空打算把 locust 的协议改成 GRPC。

**Comment by smferguson** [comment]
I'm running into the same issue. Versions:
- go 1.17
- github.com/myzhan/boomer v1.6.1-0.20210816032229-a1eced2fa7ce
- github.com/zeromq/goczmq v0.0.0-20190906225145-a7546843a315
- github.com/zeromq/czmq v4.2.2-0.20210716143126-4690d82d9218+incompatible

**Comment by myzhan** [comment]
@smferguson Thanks, it's a bug, I will fix this soon in the master branch.

**Comment by myzhan** [comment]
@smferguson The bugfix has been pushed.

**Comment by smferguson** [comment]
👍 that was _fast_. thank you!
