### ISSUE TITLE
【Question】所以slave这边的逻辑需要用go去写是吗？不再是用python。。

### ISSUE THREAD

**Issue by yisake** [myzhan/boomer#13]
如题

**Comment by yisake** [comment]
@myzhan 那这个就相当于go版本的locust，不再用python写脚本了，方便加个联系方式吗？~~

**Comment by myzhan** [comment]
可以看看这篇 blog 里面的介绍
http://myzhan.github.io/2016/03/01/write-a-load-testing-tool-in-golang/

平时工作挺忙的，不接受私聊。有问题可以在 issue 里面提，尽量及时答复。

**Comment by yisake** [comment]
多谢
