### ISSUE TITLE
我想问下怎么设置执行一定时间后自动退出boomer

### ISSUE THREAD

**Issue by wangchaosheng** [myzhan/boomer#131]
**Describe the bug**

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. centos]
 - Go Version: [e.g. 1.10]

**Additional context**

**Comment by myzhan** [comment]
目前不支持，即使做的话，我倾向于只加到 Standalone 模式，分布式压测的话，执行时间由 master 控制比较好。

**Comment by wangchaosheng** [comment]
非常感谢您如此及时的回复，目前情况是这样子的，我是一名测试，代码能力比较一般，用django起了一个后端服务，通过查数据库中的数据，生成了一个main.go的文件，然后在接口中执行go run main.go来启动这个文件，启动这个文件之后我希望加载另外一份数据，生成main2.go然后执行，此时发现无法启动，因为在终端已经启动了boomer，然后我查到了main.go的进程号然后用os.system执行kill -9 pid来终止这个程序，但是执行到这里的时候程序就会陷入等待，希望能够求解为什么这个进程在item2中kill -9 可以终止，用os.system则不可以，这个方法执行的情况就是如果之前有未关闭的boomer进程，则可以关闭，但是我第二次执行则陷入等待。另外还恳求您指导一下，如何用boomer作为压测端构建一个性能测试平台，感激不尽！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "myzhan/boomer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 下午4:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [myzhan/boomer] 我想问下怎么设置执行一定时间后自动退出boomer (#131)





 
目前不支持，即使做的话，我倾向于只加到 Standalone 模式，分布式压测的话，执行时间由 master 控制比较好。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by myzhan** [comment]
因为 boomer 会跑在前台，可能你在前面 go run main.go 的时候，已经阻塞了，可能根本没跑到 os.system 这块代码？

**Comment by wangchaosheng** [comment]
确实是跑到了的，具体的原因我也不清楚，但是我给master加了一个清除进程的接口，然后通过接口去调用一次就可以结束掉Boomer的进程了，非常感谢您写的Boomer，还想请教您一个问题，怎么限制Boomer只起一个Client去执行压测以及会有什么问题么，因为我期望能启动多个Boomer去执行不同的http压测，我目前在修改master的通信机制，让消息发到单个的Client上去执行，而不是发给所有待机的client，还有怎么用python去起多个Boomer的Client，目前我只会用go run main.go起一个boomer的client。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "myzhan/boomer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 下午5:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [myzhan/boomer] 我想问下怎么设置执行一定时间后自动退出boomer (#131)





 
因为 boomer 会跑在前台，可能你在前面 go run main.go 的时候，已经阻塞了，可能根本没跑到 os.system 这块代码？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by myzhan** [comment]
感觉你的问题，跟 boomer 没有多大关系呢。在你的方案里面，boomer 只是一个受管控的进程，换成 locust 的原生压测端，依然会有你目前遇到的问题。
