### ISSUE TITLE
新版本与老版本性能差异较大

### ISSUE THREAD

**Issue by FlyLoveFly** [myzhan/boomer#133]
相同网络环境，机器配置相同情况下，同样使用fasthttp，相同并发压测相同接口，为何得到的结果差异较大呢？
新版本
![image](https://user-images.githubusercontent.com/90945272/133873282-78bd3557-8f4a-4f24-bbc6-cfa49f541a53.png)

![image](https://user-images.githubusercontent.com/90945272/133873264-2880757a-0be9-4bb1-98d5-4ab8fd524374.png)

老版本
![image](https://user-images.githubusercontent.com/90945272/133873302-1a244def-478f-488d-abdc-2988ac880c4c.png)

![image](https://user-images.githubusercontent.com/90945272/133873317-67f65f8e-51ca-45a4-a449-ded018c081e9.png)

由上可以看出tps差了将近3倍，相较于老版本，平均响应时间增加较大是因为客户端原因么？

**Comment by myzhan** [comment]
看起来不像是客户端的问题，新版本没有改这块。不过新老版本，响应时间也不一样呀。

**Comment by FlyLoveFly** [comment]
嗯，我再进行一些详细比对测试
