### ISSUE TITLE
boomer和locust连接后不执行task

### ISSUE THREAD

**Issue by Roy-ysz** [myzhan/boomer#134]
使用文档里写的示例，boomer和locust连接正常，但是并没有task执行；
使用boomer的-run-tasks参数执行是正常的，但和locust一起就没有执行了
![image](https://user-images.githubusercontent.com/35423139/134643454-8ee7c0d0-d425-455a-915e-75cc7120e04f.png)
从locust日志也没看出任何异常
![image](https://user-images.githubusercontent.com/35423139/134643596-430d4ade-9d43-4f83-b3b8-a731fcfdb3eb.png)
大佬能帮忙看下吗

**Comment by myzhan** [comment]
你是根据什么来判断 task 没被执行？

**Comment by Roy-ysz** [comment]
> 你是根据什么来判断 task 没被执行？

依照boomer的日志，没有任何打印，而且我换成自己的task（向ES发送请求时，ES也没有接收到请求）
不过这个问题已解决，原因是boomer版本和locust版本不对齐，感谢您的回复
