### ISSUE TITLE
boomer连接locust后locust报错

### ISSUE THREAD

**Issue by yangmanyan** [myzhan/boomer#135]
myzan大神好！
         最近在使用boomer的时候，出现boomer连接locust后，locust端报错，麻烦帮忙看看是什么问题导致，谢谢！
![boomer](https://user-images.githubusercontent.com/43470085/134859637-aef07ef6-60bb-42de-b996-193bba7d6f38.png)
![locust](https://user-images.githubusercontent.com/43470085/134859683-be3e499f-dd7c-4880-9665-fcb682dff9bf.png)

**Comment by myzhan** [comment]
版本不匹配，升级一下 boomer 的版本就好
