### ISSUE TITLE
[Question] How to simulate a sequential execution of all requests instead of percentage execution.

### ISSUE THREAD

**Issue by zhwang2** [myzhan/boomer#14]
For example, the sequential execution:
Start -> Request A -> Request B -> Request C -> End

For example, the percentage execution:
Start -> Request A with 60%, Request B with 20% and Request C with 20% (Concurrent) -> End

Thx!

**Comment by myzhan** [comment]
```go
func sequential() {

    Send Request A
    // boomer.Events.Publish()

    Send Request B
    // boomer.Events.Publish()

    Send Request C
    // boomer.Events.Publish()
}

func main() {

    sequentialTask := &boomer.Task{
        Name:   "sequential",
        Weight: 10,
        Fn:     sequential,
	}

    // sequential will run concurrently
    boomer.Run(sequentialTask)

}
```

**Comment by zonghuiwang** [comment]
Thx for your quick reply!

Another question:
How to set the weight of each request in the 'sequential'?
Did the BOOMER have the analogous func as the @task() of locust?

😃

**Comment by myzhan** [comment]
1. boomer only supports setting the weight of a boomer.Task, just like locust.
2. No, golang doesn't support syntax sugar like @task.

**Comment by zhwang2** [comment]
It could be better and flexible at the test scenario if we can set the weight for each request.
Whatever, thx for your reply and nice work. 👍
