### ISSUE TITLE
locust+boomer进行压测时，如何动态控制QPS呢？(压测不中断情况下)

### ISSUE THREAD

**Issue by Elvira0326** [myzhan/boomer#145]
**Describe the bug**

**To Reproduce**
1. 目前验证的结果是，通过max-rps入参，在也测不中断情况下，QPS只能累加，不能传多少就是多少
2. 有没有已存在的方法是可以动态实现QPS，效果是：第一次传max-rps=100，qps是100；第二次传max-rps=200，qps是200，而非300
3. 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. centos]
 - Go Version: [e.g. 1.10]

**Additional context**

**Comment by myzhan** [comment]
可以自行实现一个 RateLimiter
