### ISSUE TITLE
连接locust失败，locust报错

### ISSUE THREAD

**Issue by zyklonwu** [myzhan/boomer#156]
locust日志：
[2022-01-21 10:25:21,244] edydeMacBook-Pro.local/INFO/locust.main: Starting web interface at http://127.0.0.1:8089
[2022-01-21 10:25:21,259] edydeMacBook-Pro.local/INFO/locust.main: Starting Locust 2.5.1
<gevent._socket3.socket at 0x10b88fdc0 object, fd=18, family=2, type=1, proto=0>: Invalid HTTP method: 'ÿ\x00\x00\x00\x00\x00\x00\x00\x00\x7f\x03\x01NULL\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
<gevent._socket3.socket at 0x10b94ba60 object, fd=18, family=2, type=1, proto=0>: Invalid HTTP method: 'ÿ\x00\x00\x00\x00\x00\x00\x00\x00\x7f\x03\x01NULL\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
boomer日志：
edydeMacBook-Pro:performance wubo$ ./test.out --master-host="127.0.0.1" --master-port=8089
2022/01/21 10:44:41 Boomer is built with gomq support.

没有连接成功，worker数为0

**Comment by myzhan** [comment]
locust 监听两个端口，一个 8089 是 http 协议，用于 web 界面，一个 5557 是 zeromq 协议，用于压测数据的上报。你应该是 boomer 连到 web 端口去了。

**Comment by zyklonwu** [comment]
> locust 监听两个端口，一个 8089 是 http 协议，用于 web 界面，一个 5557 是 zeromq 协议，用于压测数据的上报。你应该是 boomer 连到 web 端口去了。

谢谢，解决了
