### ISSUE TITLE
关于locust报错“An old（pre2.0）worker tried to connet.That's not going to work”的问题

### ISSUE THREAD

**Issue by freeChou** [myzhan/boomer#158]
我是用的locust版本是：2.7.3
Bommer版本是今天下载的；
启动Bommer和locust后，locust报错“An old（pre2.0）worker tried to connet.That's not going to work”
![5f3e8587a1d32a5b0656ad7e56fe118](https://user-images.githubusercontent.com/100274685/155285817-f7e836e1-3255-4223-ba38-4bceeb2ca048.png)

您能看一下这个问题么，感谢

**Comment by myzhan** [comment]
你的 boomer 版本不可能是最新的，再检查一下。

**Comment by freeChou** [comment]
非常感谢你；现在总算是能跑了；
似乎通过go get的方式下载下来的boommer并不是最新版。。替换了文件之后现在能运行了。
感谢
