### ISSUE TITLE
运行go run main.go --master-host=xxx 连接master节点，master节点报错

### ISSUE THREAD

**Issue by shiyong1989** [myzhan/boomer#160]
另一台worker主机运行o run main.go --master-host=xxx（mater节点ip），master locust服务报如下错误：
 

e4f9d2348488/ERROR/locust.runners: An old (pre 2.0) worker tried to connect (xxx). That's not going to work.

**Comment by zy7y** [comment]
我也遇到这个问题, 版本是 locust 2.8.5 boomer 1.6.0, 暂时用的处理方法是 `go get -u github.com/myzhan/boomer@master` 拉取master分支

**Comment by 91Eric** [comment]
按照你的方案确实可以奏效，但是boomer使用go get 依旧是安装的1.6.0
