### ISSUE TITLE
An old (pre 2.0) worker tried to connect (DESKTOP-UE28I2P_1910f7d5174d4474a12b381effd158ea). That's not going to work.

### ISSUE THREAD

**Issue by 91Eric** [myzhan/boomer#166]
你好，我按照readme安装了boomer+locust，locust版本为2.8.6，当我使用go get 安装boomer时，默认安装了1.6，运行测试脚本时就出现了标题所述问题，我也阅读了Issues问题列表中相同问题的解决方案，但是无法更新到所说的更高版本，是否有其他方案更新到最高版本，谢谢

**Comment by 91Eric** [comment]
参照 [https://github.com/myzhan/boomer/issues/160](url)已经暂时解决

**Comment by myzhan** [comment]
我改一下文档吧

**Comment by 91Eric** [comment]
您好，您的来信我已收到.
