### ISSUE TITLE
最新款的mac m1和最新版本的locust2.10.1 ，boomer都兼容和支持吗

### ISSUE THREAD

**Issue by nanjizhilian** [myzhan/boomer#167]
**Describe the bug**

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. centos]
 - Go Version: [e.g. 1.10]

**Additional context**

**Comment by myzhan** [comment]
你可以试试，有问题再反馈。从适用场景上，boomer 适用于服务端高并发的压测场景，在 Mac 上一般只是开发调试。

**Comment by nanjizhilian** [comment]
好的，谢谢，我试试，有问题在沟通



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月20日(周三) 中午11:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [myzhan/boomer] 最新款的mac m1和最新版本的locust2.10.1 ，boomer都兼容和支持吗 (Issue #167)




 
你可以试试，有问题再反馈。从适用场景上，boomer 适用于服务端高并发的压测场景，在 Mac 上一般只是开发调试。
