### ISSUE TITLE
无论locust使用的是什么版本均提示worker版本过低无法连接

### ISSUE THREAD

**Issue by AthlonHD** [myzhan/boomer#171]
![image](https://user-images.githubusercontent.com/72793206/184274217-65762ff9-5d70-46fe-a145-835460e31229.png)
boomer版本1.6.0和1.6.1均尝试过，locust从2.10.2-2.0.0的版本也都尝试过，locust依旧提示worker版本过低

**Comment by myzhan** [comment]
感觉你是 boomer 版本没升级成功，你点进去你本地的 boomer 代码，看看这行是什么。
https://github.com/myzhan/boomer/issues/169

**Comment by AthlonHD** [comment]
> 感觉你是 boomer 版本没升级成功，你点进去你本地的 boomer 代码，看看这行是什么。 #169

请问你指的是哪行？我这看我的boomer版本是1.6.0
![image](https://user-images.githubusercontent.com/72793206/184276334-358273d4-5fa6-475f-b19c-8e68535b0b1f.png)

**Comment by AthlonHD** [comment]
包括尝试了最新的master版本也不行
![image](https://user-images.githubusercontent.com/72793206/184276628-5540014f-9177-4da8-b1af-5c26626917d9.png)

**Comment by AthlonHD** [comment]
问题已解决：把GO下面的所有包都删除了，再安装就正常了
