### ISSUE TITLE
多个接口在一个func里执行时能否分开展示在locust中？

### ISSUE THREAD

**Issue by AthlonHD** [myzhan/boomer#172]
在一个func中尝试了用for 切片请求多个接口，也尝试了简单粗暴的在同一个func下新增了一段请求接口的代码块，但最终在locust呈现出的都是一个任务
![image](https://user-images.githubusercontent.com/72793206/184281744-62b8588c-4e3f-4d46-96ab-d77be293889d.png)

如果要达到接口按顺序请求的前提下，是否代表了写在同一个func下的接口就无法在locust分开展示？

**Comment by API-django** [comment]
这确实是让人很头疼的一个问题

**Comment by AthlonHD** [comment]
> 这确实是让人很头疼的一个问题

哈哈哈哈所以有没有什么比较好的解决办法，不然就失去了很大一部分数据

**Comment by myzhan** [comment]
这并不是什么问题，请不要把 issue 当作咨询来使用，先看看文档。

这个问题，你直接在 RecordSuccess 和 RecordFailure 传不同的参数就可以区分开。

**Comment by AthlonHD** [comment]
> 这并不是什么问题，请不要把 issue 当作咨询来使用，先看看文档。
> 
> 这个问题，你直接在 RecordSuccess 和 RecordFailure 传不同的参数就可以区分开。

抱歉没仔细看代码，目前文档的内容确实比较少哈哈哈，后续希望能协助你一起优化一下
