### ISSUE TITLE
负载变化时导致并发突增

### ISSUE THREAD

**Issue by daocoder2** [myzhan/boomer#173]
locust version: 2.8.0
boomer: master

locust原生界面记录：
![阶梯负载](https://user-images.githubusercontent.com/19505806/187451878-9979f8fc-7e04-4c7f-848d-8f77345d138b.png)

实际压测工具集成展示（tcp连接监控）：
![工具实际连接](https://user-images.githubusercontent.com/19505806/187452210-b8fc8d7b-c5f1-429b-ab09-e205ec1bf8e8.png)

看了些源码，原因可能是这里。不知道是否有后续解决方案？
> // TODO: Since locust 2.0, spawn rate and user count are both handled by master.
// But user count is divided by user classes defined in locustfile, because locust assumes that
// master and workers use the same locustfile. Before we find a better way to deal with this,
// boomer sums up the total amout of users in spawn message and uses task weight to spawn goroutines like before.

**Comment by myzhan** [comment]
有关联，但跟你理解的可能不一样。

1. locust 阶梯式变化的是并发数，不是负载，落到 boomer 这边，是用 goroutine 实现。
2. 目前在实现递增的时候，会先关掉之前的 goroutine，但不一定能及时反映在连接数的变化上。你可以理解为这些连接还存在，但是实际并发在工作的，没有这么多。
3. 后续在完善递增和递减的时候，确实可以做的更平滑一点，不用全关再全开，就是我在注释里面留的 TODO。

**Comment by daocoder2** [comment]
平滑对用户数进行调度，在httprunner中有个版本的实现，可以借鉴下，不过对已有的改动比较大。

**Comment by myzhan** [comment]
目前已经实现。
