### ISSUE TITLE
Standalone mod 运行，控制台输出没有数据

### ISSUE THREAD

**Issue by kylezk777** [myzhan/boomer#175]
**Describe the bug**

**To Reproduce**
1. Standalone mod 运行，
2.设置globalBoomer.AddOutput(boomer.NewConsoleOutput()) 

**Expected behavior**
期待控制台输出压 测数据信息，但控制台只输出了表格，其中没有信息

**Screenshots**
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/109942727/190049535-95f48274-7cb2-4992-8cf8-3868e72bd185.png">

**Environment (please complete the following information):**
 - OS: [e.g. centos]  mac pro
 - Go Version: [e.g. 1.10].   1.18

**Additional context**

**Comment by myzhan** [comment]
有添加 task 以及在 task 里面上报数据码？
