### ISSUE TITLE
能不能加个run-time 运行时间呢

### ISSUE THREAD

**Issue by qiangyanwen** [myzhan/boomer#176]
**Describe the bug**

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. centos]
 - Go Version: [e.g. 1.10]

**Additional context**

**Comment by qiangyanwen** [comment]
能不能加个run-time 运行时间呢就完美了，作者

**Comment by myzhan** [comment]
目前不考虑这个特性
1. 如果是跟 locust 一起运行，启动和结束都受 locust 管理。
2. 如果是运行在 standalone 模式，可以自行调用 Stop 来停止压测。

**Comment by qiangyanwen** [comment]
ok,谢谢大佬的回复，我很激动哈哈哈



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月17日(星期六) 下午3:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [myzhan/boomer] 能不能加个run-time 运行时间呢 (Issue #176)





 
目前不考虑这个特性
  
如果是跟 locust 一起运行，启动和结束都受 locust 管理。
 
如果是运行在 standalone 模式，可以自行调用 Stop 来停止压测。
