### ISSUE TITLE
如何能Subscribe并处理来自Master的自定义Topic

### ISSUE THREAD

**Issue by plzs** [myzhan/boomer#179]
需要Subscribe某个来自Master的自定义的Topic，并用自定义Fn处理，目前好像不支持？

**Comment by myzhan** [comment]
你是指 custom_messages 吗？现在不支持，不过要支持的话也不是很难，因为已经有 event 机制。

**Comment by plzs** [comment]
@myzhan 是的，想从master发些message给boomer worker去消费，希望能支持哈

**Comment by myzhan** [comment]
初步看了一下，因为 python 这个动态类型用 go 来实现比较麻烦。打算只允许传输固定的 data 类型，这样可以吗？

**Comment by plzs** [comment]
> 初步看了一下，因为 python 这个动态类型用 go 来实现比较麻烦。打算只允许传输固定的 data 类型，这样可以吗？
@myzhan 当然可以哈，目的就是收到massage，boomer这边golang能有办法解析即可，感谢大佬！

**Comment by myzhan** [comment]
支持了，更新一下，参考 example 试试。

**Comment by plzs** [comment]
可以了，感谢！
