### ISSUE TITLE
task可以由master通过mq传过来后，再启动slave压测吗？

### ISSUE THREAD

**Issue by hua-pan** [myzhan/boomer#183]
是否可以，如locust master发送自定义的task message给boomer，boomer收到message后自行解析，再启动slaveRunner压测吗？

**Comment by myzhan** [comment]
不太明白什么意思，是发送 task 的代码还是配置？

**Comment by myzhan** [comment]
不支持，task 是 Python 的。

**Comment by hua-pan** [comment]
ok，了解
