### ISSUE TITLE
启动参数只支持默认的 defaultboomer , 不支持自定义的 NewBoomer

### ISSUE THREAD

**Issue by xyzdev-cell** [myzhan/boomer#185]
**Describe the bug**

**To Reproduce**
1.  所有的运行参数会在init时注册
2. 所以不管什么 Boomer都显示有这些启动选项
3. 实际这些参数只在defaultBoomer中使用

**Expected behavior**
至少 mem-profile 和 cpu-profile 可以都支持上

**Screenshots**
![image](https://user-images.githubusercontent.com/63830008/207552293-8312b3ff-fdb6-4fe5-8c45-e7a94a29df55.png)

**Environment (please complete the following information):**
 - OS:wsl2 ubuntu
 - Go Version: 1.9.1

**Comment by myzhan** [comment]
这些是遗留代码，boomer 作为一个库，会尽量减少声明命令行参数，避免跟用户的冲突。
