### ISSUE TITLE
能否增加强行Quit的方式？

### ISSUE THREAD

**Issue by hua-pan** [myzhan/boomer#188]
我服务端启动的Boomer，LocustMaster异常断开时，Boomer.Quit()貌似会阻塞在wait for quit message is sent to master。
能否提供一个简单的公有方法强行退出，可以调用**b.slaveRunner.shutdown()**？thx~

**Comment by myzhan** [comment]
Boomer.Quit() 有 3 秒钟的强制退出时间，这个没有生效吗？

**Comment by hua-pan** [comment]
并没有没有生效，阻塞着

发自我的iPhone

在 2023年5月12日，11:25，myzhan ***@***.***> 写道：

﻿

Boomer.Quit() 有 3 秒钟的强制退出时间，这个没有生效吗？

**Comment by myzhan** [comment]
可以发一下 goroutine 的堆栈吗？
