### ISSUE TITLE
有没有考虑过重构boomer

### ISSUE THREAD

**Issue by nanjizhilian** [myzhan/boomer#189]
作者你很久没有更新了，我感觉你消失了，有没有考虑过重构boomer呢？我很喜欢使用boomer，对boomer的期待很高，期待您的回复

**Comment by myzhan** [comment]
有考虑，但是目前没有很强的驱动。例如需要新的功能，或者有新的架构调整。

**Comment by nanjizhilian** [comment]
我个人最近一直在看boomer的源码，也在一直思考市面上的性能测试平台，希望作者能找到强有力的驱动



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月24日(周一) 上午10:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [myzhan/boomer] 有没有考虑过重构boomer (Issue #189)




 
有考虑，但是目前没有很强的驱动。例如需要新的功能，或者有新的架构调整。

**Comment by myzhan** [comment]
精力有限，我不会把 boomer 发展为一个大而全的性能测试平台的，会一直是一个简单的库。如果你有更多的平台性需求，可以看看 httprunner，它也集成了 boomer，并且加了更多功能。
