### ISSUE TITLE
boomer run issue

### ISSUE THREAD

**Issue by brahimjarallah** [myzhan/boomer#196]
# run issue on hyprland

$ ./boomer 

/home/user/.config/boomer/config doesn't exist. Using default values. 
Using config: (min_scale: 0.01, scroll_speed: 1.5, drag_friction: 6.0, scale_friction: 4.0)
Screen rate: 60
GLX version 1.4
GLX extension: GLX_ARB_context_flush_control GLX_ARB_create_context GLX_ARB_create_context_no_error GLX_ARB_create_context_profile GLX_ARB_create_context_robustness GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_buffer_age GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_no_config_context GLX_EXT_swap_control GLX_EXT_swap_control_tear GLX_EXT_texture_from_pixmap GLX_EXT_visual_info GLX_EXT_visual_rating GLX_MESA_copy_sub_buffer GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_SGI_make_current_read GLX_SGI_video_sync 
Visual 1041 selected
X ELEVEN ERROR: BadMatch (invalid parameter attributes)
Traceback (most recent call last)
/home/user/applications/github_useful_packs/boomer/src/boomer.nim(584) boomer
/home/user/applications/github_useful_packs/boomer/src/boomer.nim(353) main
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
zsh: segmentation fault (core dumped)  ./boomer

**Comment by myzhan** [comment]
Boomer hasn't GUI related stuff, can you show me the code?

**Comment by myzhan** [comment]
Maybe you are looking for https://github.com/tsoding/boomer
