### ISSUE TITLE
'runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gaye746560359** [myzhan/boomer#20]
win10运行一段时间后报错，请问是什么原因？

![image](https://user-images.githubusercontent.com/3060035/38225702-af28e350-3728-11e8-84b0-e09a8cdff221.png)
![image](https://user-images.githubusercontent.com/3060035/38225716-c26b8364-3728-11e8-9a03-ab37f277f5ca.png)

**Comment by myzhan** [comment]
这个异常，是在 performance.go 文件的 146 行抛出来的，是你的压测代码。

boomer 运行的时候捕获了异常，并在页面上展示。

**Comment by myzhan** [comment]
检查一下 err，看这里的写法

https://github.com/myzhan/boomer/blob/master/examples/http_benchmark.go#L49
