### ISSUE TITLE
如何只使用boomer作为压测引擎

### ISSUE THREAD

**Issue by nanjizhilian** [myzhan/boomer#206]
我不想使用locust，因为感觉消耗资源，我想使用boomer做压测引擎，但是我看了boomer的源码并没有找到能获取实时的rps，压测用户数等性能指标，请问boonmer有这个方法吗

**Comment by myzhan** [comment]
standalone 模式就是，可以参考 examples。

**Comment by nanjizhilian** [comment]
但是压测的指标例如rps和压测用户数，接口响应时间这些从哪个方法中获取呢，我没找到




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月25日(星期三) 中午11:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [myzhan/boomer] 如何只使用boomer作为压测引擎 (Issue #206)















standalone 模式就是，可以参考 examples。

**Comment by myzhan** [comment]
可以看看 output.go
