### ISSUE TITLE
Unexpected RPS 

### ISSUE THREAD

**Issue by aidylewis** [myzhan/boomer#23]
I am testing out your driver under [this project](https://github.com/bbc/locust-load-tests). I am running the local Go server and setting a **1000** users to simulate with a hatch rate of **1**. The request rate is highly fluctuating. I have tested a local Go server with [Vegeta](https://github.com/tsenart/vegeta) at ~30,000 RPS. I would also expect the request rate to increment up to **1000**.

**Comment by aidylewis** [comment]
Thanks. I should have read your http example more thoroughly. However, with a **1000** users at a hatch rate of **1**, I am getting ~25,000 RPS and no incremental hatch rate.

**Comment by myzhan** [comment]
I think if you use 10 users, you will get the same RPS(~25,000). You should tune your test environment.

Running the same codes in my Macbook Pro, I got this result.

![image](https://user-images.githubusercontent.com/953781/38553570-44f1e034-3cf2-11e8-9528-232db10c545b.png)

**Comment by myzhan** [comment]
Thank you, I found a little bug while testing your code.

https://github.com/myzhan/boomer/commit/6dad7477c73f7c0f79fc0768463a0c3d84519738

**Comment by aidylewis** [comment]
No -  **thanks to you**. I think if I feed the Locust web metrics into InfluxDB/Grafana and distribute through GCP and Kubernetes, we could have a full open-source load-testing ecosystem.

**Comment by aidylewis** [comment]
> You should tune your test environment
Would I need to limit TCP conns for the user and hatch rate to make sense?

**Comment by aidylewis** [comment]
> You should tune your test environment

Just put a delay in - aaahhhhhh. Thanks.
