### ISSUE TITLE
client_gomq.go:38:26: not enough arguments in call to gomq.NewSocket

### ISSUE THREAD

**Issue by walterliang** [myzhan/boomer#25]
![image](https://user-images.githubusercontent.com/26303684/38851510-98b0edfe-4248-11e8-8e05-defe85aaa90d.png)

在windows编译slave时报错了！大佬请看下怎么解决，谢谢

**Comment by myzhan** [comment]
上游 gomq 有个不兼容的改动，我昨天 fix 了，你升级一下

go get -u github.com/myzhan/boomer
