### ISSUE TITLE
Can I set the flags like locust's min_wait and max_wait??

### ISSUE THREAD

**Issue by lanliseve** [myzhan/boomer#26]
I just used the boomer. Our test depend on the user's information.
I want to set an flag to let the boomer never run twice.
But I can't find it through the code.........

**Comment by myzhan** [comment]
You can define you own flags like [this](https://github.com/myzhan/boomer/blob/master/examples/http_benchmark.go#L83)

**Comment by lanliseve** [comment]
Thanks， let me do it
