### ISSUE TITLE
Too Many Open Files

### ISSUE THREAD

**Issue by Freyert** [myzhan/boomer#28]
Love this library so far, it really takes full advantage of our VMs' resources, but I'm running into this frequent issue where I'm creating too many file descriptors.

I've already jacked the limit through the roof as per: https://easyengine.io/tutorials/linux/increase-open-files-limit/

However I still get this. I need to do more investigation, but wanted to open an issue just in case.

**Comment by myzhan** [comment]
Any code can reproduce this problem?

If you are using golang's built-in http library, try to use keep-alive connections.

[http_benchmark](https://github.com/myzhan/boomer/blob/master/examples/http_benchmark.go) is a good example.

**Comment by Freyert** [comment]
@myzhan thanks! I was able to bump up the file limit. I think in the future we'll try to optimize connection handling, but the library we're using is fairly limited in that regard.
