### ISSUE TITLE
构造了1000并发用户，为何RPS一直在50左右上不去？

### ISSUE THREAD

**Issue by walterliang** [myzhan/boomer#29]
而且还报错：
![image](https://user-images.githubusercontent.com/26303684/39865243-c9a9304a-547e-11e8-98dc-dcc7e9e83c46.png)
![image](https://user-images.githubusercontent.com/26303684/39865916-200e6cb4-5481-11e8-9868-29e525a424aa.png)
大佬帮忙看下，谢谢！

**Comment by myzhan** [comment]
你代码里面 panic 了，没有代码定位不了问题

**Comment by walterliang** [comment]
脚本在这，请看下https://github.com/walterliang/android_loadtest/blob/master/loadtest1.go

**Comment by walterliang** [comment]
测试用的服务器，放心压

**Comment by myzhan** [comment]
看这里 https://github.com/myzhan/boomer/blob/master/examples/http_benchmark.go

压测的时候，最好用长连接

**Comment by walterliang** [comment]
我请求头是keep-alive啊

**Comment by myzhan** [comment]
没用，HTTP 是君子协议。查 golang 的 http client 文档，里面有说客户端怎样复用连接。
