### ISSUE TITLE
locust页面点击stop后，rps会一直降到0，无法统计到停止前的rps

### ISSUE THREAD

**Issue by wcycxp** [myzhan/boomer#30]
locust页面点击stop后，rps会一直降到0，无法统计到停止前的rps。如果使用locust发压，停止后可以统计到停止前的rps

**Comment by myzhan** [comment]
要这个效果？在我这边没有重现。
![image](https://user-images.githubusercontent.com/953781/41136978-6b3c1fec-6b0b-11e8-82df-2f4aa55b3ec0.png)

**Comment by wcycxp** [comment]
@myzhan  好的，我再试试，我把来的库删除后，重新安装时怎么报错了
![image](https://user-images.githubusercontent.com/23310275/41154093-8f7de2ec-6b4b-11e8-8706-49706af2108e.png)

**Comment by myzhan** [comment]
升级一下 gomq 吧，这个是因为它做了一些不兼容的改动

go get -u github.com/zeromq/gomq

**Comment by wcycxp** [comment]
@myzhan  我在本地执行时，stop后rps不会降到0，但是把脚本都放到阿里云服务器上执行时，点stop后rps就会一直慢慢降到0.
![image](https://user-images.githubusercontent.com/23310275/41219316-7ff4315e-6d90-11e8-86f8-aec86acc1d25.png)

**Comment by wcycxp** [comment]
啥意思？

**Comment by myzhan** [comment]
能否提供代码，能稳定重现的？

**Comment by wcycxp** [comment]
package main

import "github.com/myzhan/boomer"
import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"strings"
	//"fmt"
	"crypto/tls"
	"time"
)

var client *http.Client
var disableCompression bool
var disableKeepalive bool
var timeout int

func fea() {
	//发送请求
	req, err := http.NewRequest("GET","http://mock.eolinker.com/U8MDwXVd24c43df078d1586f43a238ca8469c901ab6414e?uri=/test",nil)
	if err != nil {
 		boomer.Events.Publish("request_failure", "http", "req", 123, err)
 	}
	start := boomer.Now()
	resp, err := client.Do(req)
	elapsed := boomer.Now() - start
	if err != nil || resp.StatusCode != http.StatusOK {
		boomer.Events.Publish("request_failure", "http", "foo", elapsed, "status wrong")
	} else {
		//接收到返回数据
		defer resp.Body.Close()
		body, _ := ioutil.ReadAll(resp.Body)
		lenth := len(body)
		da := strings.Contains(string(body), "data")
		if da == false {
			boomer.Events.Publish("request_failure", "http", "foo_da", elapsed, string(body))
		} else {
			//解析返回数据
			var result map[string]interface{}
			json.Unmarshal(body, &result) //json转为map}
			re := result["result"]
			// _, ok := result["data"]
			if re == false {
				boomer.Events.Publish("request_failure", "http", "foo_re", elapsed, string(body))
			} else {
				boomer.Events.Publish("request_success", "http", "foo", elapsed, int64(lenth))
			}
		}
		//fmt.Println(result["errorMessage"])

	}
	/*
	   Report your test result as a success, if you write it in locust, it will looks like this
	   events.request_success.fire(request_type="http", name="foo", response_time=100, response_length=10)
	*/
	//boomer.Events.Publish("request_success", "http", "foo", elapsed, int64(10))
}

func main() {
	http.DefaultTransport.(*http.Transport).MaxIdleConnsPerHost = 2000
	tr := &http.Transport{
		TLSClientConfig: &tls.Config{
			InsecureSkipVerify: true,
		},
		MaxIdleConnsPerHost: 2000,
		DisableCompression:  disableCompression,
		DisableKeepAlives:   disableKeepalive,
	}
	client = &http.Client{
		Transport: tr,
		Timeout:   time.Duration(timeout) * time.Second,
	}

	task1 := &boomer.Task{
		Name:   "fea",
		Weight: 10,
		Fn:     fea,
	}

	// task2 := &boomer.Task{
	// 	Name:   "bar",
	// 	Weight: 20,
	// 	Fn:     bar,
	// }

	boomer.Run(task1)

}

**Comment by wcycxp** [comment]
上面的代码，我放在服务器上跑时，点stop后，rps就会一直慢慢降到0

**Comment by wcycxp** [comment]
额，这个有啥解决办法么，为啥windows上跑的时候，stop后没有问题

**Comment by myzhan** [comment]
帮忙看看，是不是掉为 0 的时候，requests 计数不涨，fails 计数涨

**Comment by wcycxp** [comment]
并不是的，stop后requests和fails计数都还会涨

**Comment by myzhan** [comment]
目前 boomer 启动后，每三秒向 locust 上报一次统计信息，即使没有数据，这个行为和 locust 保持一致。这种情况，可能是 http 请求响应较慢，导致结果上报有延迟，在 stop 后，依然有数据上报。

**Comment by myzhan** [comment]
在 Locust 0.9.0 版本复现这个问题，应该是 Locust 新代码导致，待排查。
