### ISSUE TITLE
Get http://localhost:8080: readLoopPeekFailLocked: read tcp [::1]:60834->[::1]:8080: read: connection reset by peer

### ISSUE THREAD

**Issue by aidylewis** [myzhan/boomer#32]
Running the example test [here](https://github.com/bbc/locust-load-tests) and **10000** users with a hatch rate of **50**.  I get:
```
readLoopPeekFailLocked: read tcp [::1]:60834->[::1]:8080: read: connection reset by peer
```
I have had it running at 30,000 users with one Boomer. 

mac OS Sierra, 8GB, 2 cores

Thanks

**Comment by aidylewis** [comment]
Ran:
```
 go get github.com/myzhan/boomer
```
Now:
```
Get http://localhost:8080: net/http: HTTP/1.x transport connection broken: http: putIdleConn: too many idle connections
```

**Comment by myzhan** [comment]
Don't put a time.Sleep in your code, you may need boomer's max RPS support.

Try to run with --max-rps 10000.

**Comment by aidylewis** [comment]
Thanks, I noticed that last night. Any chance of a linear ramp-up to 10,000 RPS?

**Comment by myzhan** [comment]
Try this

https://github.com/myzhan/boomer/blob/master/examples/pacing_rps.go

**Comment by aidylewis** [comment]
Do you feel there is any value to the Locust UI now, especially users and hatch rate?

**Comment by myzhan** [comment]
You mean https://github.com/locustio/locust/issues/646 ?

Locust has no support for RPS control, so far.

**Comment by aidylewis** [comment]
* go get github.com/myzhan/boomer
* Removed to the 1 second sleep
* go build -o a.out main.go
* locust -f dummy.py --master --master-bind-host=127.0.0.1 --master-bind-port=5557
* ./a.out --max-rps 20000 --master-host=127.0.0.1 --master-port=5557 --rpc=zeromq
*  go run server.go

http://localhost:8089
Swarm 20000 and hatch rate of 100. 

```
2018/06/21 09:56:24 Max RPS that boomer may generate is limited to 20000
2018/06/21 09:56:24 Boomer is built with gomq support.
2018/06/21 09:56:24 ZMQ sockets connected
2018/06/21 09:56:24 Boomer is connected to master(127.0.0.1:5557|5558) press Ctrl+c to quit.
2018/06/21 09:58:56 Hatching and swarming 20000 clients at the rate 100 clients/s...
2018/06/21 09:59:01 Get http://localhost:8080: read tcp [::1]:60849->[::1]:8080: read: connection reset by peer
```

**Comment by aidylewis** [comment]
I will try the pacing.

**Comment by aidylewis** [comment]
Copied your pacing_rps.go and added as a task:

https://github.com/bbc/locust-load-tests/blob/master/examples/urlbash/url_bash.go#L30-L48

We have the same package - main, so built both files

```
go build .
```

As soon as I run ```./a.out```, the ```log.Println("Current RPS", currentRPS)```
prints to stdout (so probably comment that out and the publish to Locust) 

When I kick the test off through the locust UI (10000, 100), I eventually get 

```
Get http://localhost:8080: read tcp [::1]:63884->[::1]:8080: read: connection reset by peer
```

Thanks

**Comment by aidylewis** [comment]
Ah yes. Call my function within your **coworker**.

**Comment by aidylewis** [comment]
Sorry for the spam everyone, but I think this is what you are inferring. 
https://github.com/bbc/locust-load-tests/tree/master/examples/urlbash

However, the hatch rate, Locust RPS and server RPS are out of sync. 

* 1000 users with a hatch rate of 1 in the  Locust UI. 
* --max-rps 1000

**Comment by myzhan** [comment]
The hatch rate is related to the number of goroutines(users), not the RPS. In this case, 10 users or 1000 users, make no difference.

If you run with --max-rps 1000, the RPS of both locust and server, should be very close.

**Comment by aidylewis** [comment]
And they are, thank you very much. Do you think we could also increase file descriptors, decrease TCP TIME_WAIT and increase idleConnections?

**Comment by myzhan** [comment]
Only if you want to know how many long connections the server can handle, not the max requests it can process per second.

**Comment by aidylewis** [comment]
I am willing to pay a bounty to add a linear ramp-up as a command line flag (e.g.) -rps=1 which would increase to the --max-rps. adrian underscore lewis at hushmail dot com.

**Comment by myzhan** [comment]
Adding a command line flag (e.g.) -rps-rate=1 which would increase from zero to -max-rps, or infinity if max-rps is disabled.

**Comment by aidylewis** [comment]
Hi @myzhan Shall I put the request on here: https://www.bountysource.com?

**Comment by myzhan** [comment]
Cool, thanks for letting me know such a website.
