### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by robertXin** [myzhan/boomer#33]
./a.out --master-host=127.0.0.1 --master-port=5557 --rpc=socket
2018/06/21 14:57:20 Boomer is built with gomq support.
2018/06/21 14:57:20 Boomer is connected to master(127.0.0.1:5557) press Ctrl+c to quit.
fatal error: runtime: out of memory

内存不足？？？？

**Comment by myzhan** [comment]
有代码吗？

**Comment by robertXin** [comment]
就是main.go的代码

**Comment by robertXin** [comment]
go1.10
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x96e88a, 0x16)
	/usr/local/go/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc420200000, 0xff000000, 0x0, 0xc30438)
	/usr/local/go/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0xc17100, 0xff000000, 0x0)
	/usr/local/go/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0xc17100, 0x7f800, 0x0)
	/usr/local/go/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0xc17100, 0x7f800, 0xc30448, 0x0)
	/usr/local/go/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0xc17100, 0x7f800, 0xc420020101, 0x7f920ef0fde0)
	/usr/local/go/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0xc17100, 0x7f800, 0xc420010101, 0x7f920ef0fe58)
	/usr/local/go/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0xff000000, 0xc420060101, 0x1)
	/usr/local/go/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1175

**Comment by myzhan** [comment]
这个，是不是你系统内存已经用完了？
