### ISSUE TITLE
Prometheus and Grafana

### ISSUE THREAD

**Issue by ghost** [myzhan/boomer#34]
I was thinking of writing some documentation on Prometheus, exporters and Grafana and submit a PR. WDYT? The idea I suppose is to bypass the Locust UI. I think the node and stats exporter could be exampled. As you mention the swarm rate is go routines and we have the max rate built in via your flag.

**Comment by myzhan** [comment]
Any PR is welcome. In my daily work, I did similar things with Jenkins and Docker, and it's doable.

**Comment by myzhan** [comment]
Another option with the WebUI.

1. Start 100 users with a hatch rate of 10.

```bash
curl --data "locust_count=100&hatch_rate=10" "http://locust:8089/swarm"
```

2. Collect json stats every 2 seconds, like the ajax request.

```bash
for ((i=1; i<= 300; i++));
do
  curl -s "http://localhost:8089/stats/requests" >> locust-stats.json;
  echo "" >> locust-stats.json;
  sleep 2;
done
```

3. Stop the test.

```bash
curl -s "http://localhost:8089/stop"
```

You will get locust-stats.json, easier to parse.

**Comment by aidylewis** [comment]
Thanks for the suggestion but I am thinking the boomer rps flags and the locust user/ swarm rate could be confusing for the load tester, and I am leaning towards no interaction with the Locust UI. Although I could be heading in the wrong direction.

**Comment by aidylewis** [comment]
Yeah, Looks like a real hassle parsing stout or using tee. Getting broken connection and peer resets when using the Locust UI.
