### ISSUE TITLE
[Feature] --duration flag

### ISSUE THREAD

**Issue by ghost** [myzhan/boomer#36]
I was thinking of a test duration flag (--duration=10m, -d=10m). This I think would just be a matter of a timer and an os.Exit(0). What are your opinions?

**Comment by myzhan** [comment]
It's easy to support this, but I often run in distribute mode with multiple boomer instances, I think this feature should be added to locust.

**Comment by aidylewis** [comment]
Via locustio.slack
@cgoldberg [2:03 PM] 
@aidylewis we already have it in master branch..  `--run-time` or `-t`   .. example: `-t 1h30m`

**Comment by myzhan** [comment]
Good to know, but it only works with --no-web.

**Comment by aidylewis** [comment]
Aaaahhhh. i have just moved to your curling and JSON output. I don't think I really want to use the locust UI, but can't parse stdout from another process.  I'll think I return to metric stdout and use Prometheus exporters for non-http stuff (E.g MongoDB, SQS or OS monitoring)
