### ISSUE TITLE
[Feature Request] Every flag for minute pacing? 

### ISSUE THREAD

**Issue by aidylewis** [myzhan/boomer#37]
We have **—request-increase-rate** and **--max-rps** which is great. But I wonder if we add another command line flag **--every**. 

So, I have an example that would increase by 10 messages (SQS) every X number of minutes. 

E.g. —request-increase-rate 10 —every 5m

That will go on until I either manually stop the test through the GUI or use the new Locust time duration flag.

Willing to pay bounty.

**Comment by myzhan** [comment]
I prefer to change --request-increase-rate and add support like this.

E.g. --request-increase-rate 10/5m

The default interval is 1s, --request-increase-rate 1 is equal to --request-increase-rate 1/s.

What do you think?

**Comment by aidylewis** [comment]
More elegant than what I proposed.

**Comment by myzhan** [comment]
Please give it a try.

https://github.com/myzhan/boomer/commit/e3065b9fe689e9c393ce949aa5aa3c6d49dcfec5

**Comment by aidylewis** [comment]
Testing on minutes and looks OK to me. 
```
./a.out --request-increase-rate 10\1m --master-host=127.0.0.1 --master-port=5557 --rpc=zeromq

// go run server.go
```
2018/07/13 11:09:04 Rate: 1
2018/07/13 11:09:05 Rate: 11
2018/07/13 11:09:06 Rate: 10
2018/07/13 11:09:07 Rate: 10
2018/07/13 11:09:08 Rate: 10

2018/07/13 11:10:03 Rate: 10
2018/07/13 11:10:04 Rate: 20
2018/07/13 11:10:05 Rate: 20
2018/07/13 11:10:06 Rate: 20
2018/07/13 11:10:07 Rate: 20
2018/07/13 11:10:08 Rate: 20
```
Thanks

**Comment by aidylewis** [comment]
Unfortunately, the pacing doesn't seem to working using SQS:
```go
// Usage: ./a.out --request-increase-rate 10/1m --master-host=127.0.0.1 --master-port=5557 --rpc=zeromq

package main

import (
    "github.com/aws/aws-sdk-go/aws"
    "github.com/aws/aws-sdk-go/aws/session"
    "github.com/aws/aws-sdk-go/service/sqs"
    "github.com/myzhan/boomer"
)

func sender() {
    sess := session.Must(session.NewSessionWithOptions(session.Options{
        SharedConfigState: session.SharedConfigEnable,
    }))

    svc := sqs.New(sess)

    start := boomer.Now()

    qURL := "<queueUrl>"

    // we probably need to do something with this result tuple
    _, err := svc.SendMessage(&sqs.SendMessageInput{
        MessageBody: aws.String("Aidy Lewis: Message body Test"),
        QueueUrl:    &qURL,
    })

    elapsed := boomer.Now() - start

    if err != nil {
        boomer.Events.Publish("request_failure", "sqs", "send_message", elapsed, err)
        return
    }

    // we need a base int type for the last parameter
    boomer.Events.Publish("request_success", "sqs", "send_message", elapsed, int64(10))
}

func main() {
    task := &boomer.Task{
        Name: "sender",
        Fn:   sender,
    }

    boomer.Run(task)
}
```

**Comment by myzhan** [comment]
Having a holiday without computer, and not familiar with the sdk of sqs. I will look into this ASAP. And before that, please make sure you have run go get -u github.com/myzhan/boomer.

**Comment by aidylewis** [comment]
Thanks. I will try to debug it through delve. I've used go get on this project to include dependencies. Tried unsuccessfully to set ```requestIncreaseInterval = time.Minute```

**Comment by myzhan** [comment]
Hi, any progress?

**Comment by aidylewis** [comment]
Sorry, just looked at this. Didn't manage to achieve a slower request rate than seconds (for some reason).

**Comment by myzhan** [comment]
What does the chart look like when you run test with sqs and set request-increase-rate to 10/1m?
