### ISSUE TITLE
怎么设置min_wait和max_wait来控制每个用户执行两个任务之间的等待时间？

### ISSUE THREAD

**Issue by spiderpoison** [myzhan/boomer#38]

**Comment by myzhan** [comment]
目前还不支持这两个参数

**Comment by myzhan** [comment]
多任务的话，按照 weight 来分 goroutine，每个 goroutine 里面循环跑 Fn 对应的函数。

如果你需要间隔时间，在 Fn 对应的函数里面自行 sleep 一下。
