### ISSUE TITLE
如果我想测试长连接，需要先初始化连接的情况，应该怎么搞？

### ISSUE THREAD

**Issue by spiderpoison** [myzhan/boomer#39]
locust是一个client就是一个类，可以在类里保存状态，boomer只有func()，要怎么搞，没太想明白

**Comment by myzhan** [comment]
之前没把 Fn 设计为一个实例方法，要实现这种场景确实比较别扭。如果你的连接可以多个 goroutine 共用，那么可以在调用 boomer.run 之前，初始化好一个连接，或者连接池。

**Comment by spiderpoison** [comment]
那client的id是否能提供，比如我做了1000个链接，启1000个client，测试协议收发的延迟时间的话，我希望能把连接和client一一对应上

**Comment by myzhan** [comment]
目前Fn对应的函数被调用的时候，是不知道client的。你可以在函数里面先获取一个你自己定义的client对象，publish的时候第二第三个函数填clientID？

**Comment by spiderpoison** [comment]
你的意思是我在Fn里随机获取一个client？但我怎么保证不同的Fn占有的是不同的client呢

**Comment by myzhan** [comment]
按照你这个描述，比较像在压测一个使用TCP协议的聊天室。可以看看example目录下的udp_proxy，绕过无状态的Fn，单纯使用Publish结果的功能。

**Comment by spiderpoison** [comment]
我参考了udp_proxy，这样的话locust页面就不能控制发起的机器人数量，而是由程序控制了。。。这样locust页面感觉意义还有多大？用来看charts和收集一下错误吗？

**Comment by myzhan** [comment]
目前这一块只能使用方想办法了，之前有打算提供一个类似于 TLS 的对象，给用户存放上下文，不过还没时间去弄。
