### ISSUE TITLE
是否考虑尝试在boomer基础上，稍作修改，让他适合socket压测

### ISSUE THREAD

**Issue by spiderpoison** [myzhan/boomer#41]
我在boomer基础上，修改Run的传入参数为如下TaskClient
type TaskClient interface {
	Copy() TaskClient
	OnStart(idx int) bool
	Tasks() []*Task
	OnStop()
}
即有个struct可以用来保存socket的handler

用修改后的版本做过压测，基本没什么问题

**Comment by myzhan** [comment]
你的实现，是多个 goroutine 共用一个 TaskClient 对象？还是每个 goroutine 都有一个 TaskClient 对象，里面分别调用一下 OnStart 和 OnStop？

欢迎提交 PR！

**Comment by myzhan** [comment]
可以暴露多一个 API，不要复用 Run，保持兼容性

**Comment by spiderpoison** [comment]
每个client会调用copy拷贝一个TaskClient出来，然后用新的TaskClient进行onstart和onstop

**Comment by myzhan** [comment]
相对于 copy，传一个构造方法给 boomer 是否更好，可以在构造方法或者 OnStart 里面初始化连接。

**Comment by 15951836388** [comment]
@myzhan 大佬，可以支持一下socket和websocket吗？

**Comment by myzhan** [comment]
@15951836388 目前也支持的，你可以自己维护一个连接池，然后 Fn 函数从连接池中取连接。

不过这样实现比较麻烦，也很绕，我在想更合适的 API。

**Comment by myzhan** [comment]
目前这个问题可以这样解决。

https://github.com/myzhan/boomer/commit/e203e776c5125088221ec45b024f678817dc2645

**Comment by eyotang** [comment]
@spiderpoison 我是直接扩展了Fn，加了ctx（concurrentmap）和初始化任务。方便游戏压测时，建立tcp连接，存储机器人信息，适应异步框架。
仅做参考：https://github.com/eyotang/boomer

**Comment by myzhan** [comment]
@eyotang 你这样更易用，可以考虑在 Fn 之外，加多一个字段，支持 ctx。

**Comment by eyotang** [comment]
有微信不？eyotang2016




在2020年08月17日 20:56，myzhan 写道：

@eyotang 你这样更易用，可以考虑在 Fn 之外，加多一个字段，支持 ctx。
