### ISSUE TITLE
相同并发情况下多个slave比一个slave测出来的tps低很多

### ISSUE THREAD

**Issue by frogking326** [myzhan/boomer#43]
**Describe the bug**
对同一接口压测，并发都是10，
启用一个slave情况，TPS:120
启用两个slave情况，TPS：65
为何多个slave反而比单个slave的TPS低了一半呢？

**Comment by myzhan** [comment]
在压测代码和接口代码没问题的情况下，不应存在这种情况。目前提供的信息不足以定位问题。

**Comment by frogking326** [comment]
刚才又试了下，
两个slave的情况下，其中一个slave和master放在同一台服务器，另外一个slave在一台机器，此时tps:60-70
如果master在一台独立服务器上，另外两个slave分别放在另外两台服务器上，此时tps:120-130

**Comment by frogking326** [comment]
如果一个slave情况下，slave和master放在同一台服务器，此时tps：120-130.
代码应该没问题，方便的话，您也可以试一下上述场景是否存在类似问题

**Comment by myzhan** [comment]
你看看是不是两个 slave 都收到了压测指令。如果下发了 10 个并发，应该每个 slave 都启动 5 个 goroutine。

**Comment by frogking326** [comment]
都收到了压测指令
A slave:
2018/11/27 15:53:35 Boomer is built with gomq support.
2018/11/27 15:53:35 Boomer is connected to master(192.168.110.28:5557|5558) press Ctrl+c to quit.
2018/11/27 15:54:18 Hatching and swarming 5 clients at the rate 5 clients/s...

B slave（master也在这台机器）:
2018/11/27 15:44:33 Boomer is built with gomq support.
2018/11/27 15:44:33 Boomer is connected to master(192.168.110.28:5557|5558) press Ctrl+c to quit.
2018/11/27 15:44:44 Hatching and swarming 5 clients at the rate 5 clients/s...

**Comment by frogking326** [comment]
会不会和这个bind-host有关？
locust -f dummy.py --master --master-bind-host=192.168.110.28 --master-bind-port=5557

go run bankprepay.go  --master-host=192.168.110.28 --master-port=5557

**Comment by myzhan** [comment]
关系不大，只要 slave 能连上去就好。可否麻烦在你的环境跑一下，看看是否存在同样的问题。

https://github.com/myzhan/boomer/blob/master/examples/main.go

这个应该是最小例子。

另外，看看是不是有 failure 的情况，因为 failure 不算在 RPS 里面。

**Comment by myzhan** [comment]
可以改一下 boomer 的代码，在这里 https://github.com/myzhan/boomer/blob/master/runner.go#L352 把 data 打印出来，看看 slave 上报的数据是否正常。

**Comment by myzhan** [comment]
你有一台施压机的系统时间不对，其实 slave 是有上报结果的，但是 master 会忽略掉系统时间和自身系统时间差太多的结果。

那个有问题的施压机分了 5 个 goroutine，但是它上报的结果被丢弃了。

其实两种情况，你接口处理的 TPS 都是 120-130 左右。

**Comment by frogking326** [comment]
恩，确实是这个原因

**Comment by frogking326** [comment]
环境因素

**Comment by frogking326** [comment]
环境因素

**Comment by frogking326** [comment]
环境因素
