### ISSUE TITLE
tcp 连接并不平均

### ISSUE THREAD

**Issue by yuyongID** [myzhan/boomer#44]
**描述：** 使用boomer进行socket压测，如果定义每秒100个用户的话，通过抓包发现boomer生成的客户端在每秒的前100ms就把100个用户都创建完毕并建立连接了。并等到下一个1s的到来，也会在前100ms创建完成。

**问题：** 这样的测试效果就不是100人/s，而是1人/ms，这样对被测服务器考验是不一样的。

**建议：** 根据master的每秒并发数，将goroutine的生成时间间隔平均到整个1s中，而不是集中在1s的最前面全部生成。

**Comment by myzhan** [comment]
> 根据master的每秒并发数，将goroutine的生成时间间隔平均到整个1s中
目前就是这样做的。

另外，跟 locust 原生每个协程一个 Task 对象不一样，boomer 中的 task.Fn，是多协程共享的，你看看是不是这样原因？

boomer 没有自带客户端，有具体测试代码吗？

**Comment by yuyongID** [comment]
> > 根据master的每秒并发数，将goroutine的生成时间间隔平均到整个1s中
> > 目前就是这样做的。
> 
> 另外，跟 locust 原生每个协程一个 Task 对象不一样，boomer 中的 task.Fn，是多协程共享的，你看看是不是这样原因？
> 
> boomer 没有自带客户端，有具体测试代码吗？

我是自己写的socket客户端，然后把客户端的初始化和测试触发都集合到一个函数里，作为boomer一个task.Fn，再由llocust master来触发并发数。
`
func locustTest() {
	// get user data from test data queue
	data, ok := <-zmqcli.Queue
	if ok != true {
		log.Println("zmqcli is empty")
		return
	}
	iclient.testScene(data)
}
func main() {
	go zmqcli.GetReady()  // init data quene and get test data
	task1 := &boomer.Task{
		Name: "test1",
		Weight: 100,
		Fn:   locustTest,
	}
	boomer.Run(task1)
}
`
这样调用之后，所有iclient客户端都会集中在前100ms跟服务器建立socket，如下图显示的是所有客户端在测试的第一个1s所发出的tcp第一次握手统计。
![2018-12-07 3 06 53](https://user-images.githubusercontent.com/13815334/49632755-d5140280-fa31-11e8-9546-29e6c2e3d2bd.png)

**Comment by myzhan** [comment]
这样做没问题，不过我没看到你建立连接的逻辑在哪里。locustTest 函数会在一个无限循环里面被调用，被多个 goroutine 同时调用。是否只有一个 goroutine 在不断调用 locustTest 函数的时候，你会建立多个连接？

**Comment by yuyongID** [comment]
> 这样做没问题，不过我没看到你建立连接的逻辑在哪里。locustTest 函数会在一个无限循环里面被调用，被多个 goroutine 同时调用。是否只有一个 goroutine 在不断调用 locustTest 函数的时候，你会建立多个连接？

还以为我使用方法有问题，没问题就好。

这个我的建立连接的逻辑都比较多，都封装在iclient的里面了，执行italient.testScene(data)之后，iclient就会建立连接，并且会一直占用这个goroutione用来收发消息，没有返回的。消耗完通道zmqcli.Queue的data数据之后，就会堵塞主进程，不进行下一个轮次的调用了。所有测试都依靠拉起来的所有goroutine来进行。

我觉得既然通过boomer能拉起来这个多个连接，应该就不是只有一个goroutione不断调用locustTest函数。

并且，我尝试在您的boomer源码里runner.go的spawnGoRoutines()的147行增加了根据 r.hatchRate 均分1s的sleep之后
``` golang
time.Sleep(time.Duration(1000/r.hatchRate) * time.Millisecond)
```
还删除前面三行
``` golang
if i%r.hatchRate == 0 {
	time.Sleep(1 * time.Second)
}
```
能达到预期1s均分100个（100ms一个）tcp首次握手的结果。

**Comment by yuyongID** [comment]
> 懂你意思了，原本这个 hatchRate 的意思，是一秒增加的 goroutines 数量，所有 goroutines 都是短时间创建出来的，并没有平摊时间片。目前这个实现，跟 locust 是保持一致的。
> 
> 你这是一个合理的场景，欢迎提交 PR，在原来的基础上，增加一种 hatch 方式。 :D

 同样的压测我也用python实现过，使用locust slave来并发不会出现这样极短时间时间创建出所有客户端连接的情况。我觉得这应该是python的“慢”才没有发生这样情，也是我们boomer使用golang的“快”才需要单独处理这样的情况。周一我尝试一下提交PR，不过我是go新手，代码质量不高就是了。
(＃－－)/ .

**Comment by myzhan** [comment]
你这个场景，也可以用一个 channel 来当连接池，在 locustTest 函数里面从 channel 获取到连接再发请求。然后 main 函数里面开一个 goroutine，按照固定的速率来新建连接，然后放到 channel 中去。

**Comment by yuyongID** [comment]
> 你这个场景，也可以用一个 channel 来当连接池，在 locustTest 函数里面从 channel 获取到连接再发请求。然后 main 函数里面开一个 goroutine，按照固定的速率来新建连接，然后放到 channel 中去。

我之前也有尝试过类似的的方案，但都只能固定一个频率来触发goroutine。由于只有boomer的内部知道master下发的r.rate。所以，如果不改动boomer代码的吐出rate的话，就不好动态设置这个值了，毕竟不是每次压测都是要求一样的并发。

既然要改动boomer的代码的话，还不如直接让boomer来直接管理这个触发goroutine的频率了。
