### ISSUE TITLE
是否考虑暴露一个API引出master下发的stop指令

### ISSUE THREAD

**Issue by yuyongID** [myzhan/boomer#46]
在Fn的函数调用了自己的socket client，拉起了多个goroutine来处理收发包和心跳维持。boomer能正常拉起所有客户端。
但是，收到master的stop消息的时候，这些拉起的goroutine没有办法获取到这个stop指令，无法停止。

**Comment by myzhan** [comment]
boomer 内置了一个 EventBus，例如这个用法 https://github.com/myzhan/boomer/blob/master/boomer.go#L116

可以考虑 runner 在 start 和 stop 的时候分别发布 boomer:start 和 boomer:stop 事件给用户订阅。

**Comment by myzhan** [comment]
这个事件可以带上一些信息，你看看需要些啥？

**Comment by yuyongID** [comment]
> 这个事件可以带上一些信息，你看看需要些啥？

好的，我看看能不能正常停掉所有goroutine

**Comment by myzhan** [comment]
补充了一个 boomer:stop 事件，https://github.com/myzhan/boomer/commit/3b16b09341c0a9c2ec9e7729e4d7720f0cf20c78

用法你可以参考测试用例里面的，一般做法，你可以创建一个 channel，自己创建的 goroutine 都 select 在这个 channel 上面，然后收到 boomer:stop 事件的时候，close 这个 channel，达到广播的效果。

**Comment by yuyongID** [comment]
> 补充了一个 boomer:stop 事件，[3b16b09](https://github.com/myzhan/boomer/commit/3b16b09341c0a9c2ec9e7729e4d7720f0cf20c78)
> 
> 用法你可以参考测试用例里面的，一般做法，你可以创建一个 channel，自己创建的 goroutine 都 select 在这个 channel 上面，然后收到 boomer:stop 事件的时候，close 这个 channel，达到广播的效果。

大佬，创建一个 channel 通过订阅 boome:stop 事件，在 master stop 过一次之后，自己的 gouroutine 确实可以正常退出。但是 master 再 start，由于没有 start 事件，自己创建的 goroutine select 的channel 没有办法再次初始化，无法再拉起第二次 start 需要的的 goroutine。

试了一下，每个测试用例的client里面单独做一个channel来处理这个监听事件并每次都初始化属于client的stop channel。
这种做法也可以在第一次测试 stop 所有 gorouine 正常退出。第二次测试 start 也能正常拉起。但是第二次的 stop 却出现【panic: close of closed channel】的 panic。
打印出日志，发现事件触发的 close 操作想要关闭的 channel 并不是第二次测试 client 自己的初始化的stop channel。而是第一批 client 的 stop channel。不知如何是好了。

**Comment by myzhan** [comment]
> 由于没有 start 事件，自己创建的 goroutine select 的channel 没有办法再次初始化
这个你可以考虑在 Fn 里面用 sync.Once 来初始化。

> 但是第二次的 stop 却出现【panic: close of closed channel】的 panic
如果是 boomer 里面的 panic，可以把异常栈发出来看看。

**Comment by yuyongID** [comment]
> > 由于没有 start 事件，自己创建的 goroutine select 的channel 没有办法再次初始化
> 
> 这个你可以考虑在 Fn 里面用 sync.Once 来初始化。
> 
> > 但是第二次的 stop 却出现【panic: close of closed channel】的 panic
> 
> 如果是 boomer 里面的 panic，可以把异常栈发出来看看。

 使用 sync.Once 可以正常初始化了，达到预想的功能。至于第二个问题的那个 panic，是我测试 client 代码的 panic 可以忽略了。谢谢大佬
