### ISSUE TITLE
locust+boomer进行grpc压测的咨询

### ISSUE THREAD

**Issue by zbye** [myzhan/boomer#51]
**Describe the bug**
你好，
我在进行gprc接口的压测，在公司虚拟机环境中尝试用了locust/jmeter，但6台机器所产生的最高请求量只有约7w/s，希望能用找一种能提供更高并发量、模拟很多用户的解决方案。 偶然看到本项目，希望能用boomer+locust进行grpc压测，下面这种方式可行吗？
（单连接不断发请求^_^）

**Expected behavior**

````
package main
import boomer "github.com/myzhan/boomer"

import (
	"context"
	"demo/HelloWorld"
	"google.golang.org/grpc"
)

func grpc_test(){
    conn, err := grpc.Dial("10.187.160.26:10002", grpc.WithInsecure())

    if err != nil {
       boomer.Events.Publish("request_failure","Connection","grpc",0.0,err)   
    }

    defer conn.Close()
    c := rpcdemo_service.NewHelloWorldServiceClient(conn)        // get the connection

    // for-loop
    for {
        startTime := boomer.Now()
        ctx := context.Background()
        res, err := c.SayHello(ctx, &rpcdemo_service.Person{FirstName: "first_name", LastName: "last_name", Time: "5"})
        endTime := boomer.Now()

        if err != nil {
            boomer.Events.Publish("request_failure","SayHello", res ,0.0,err.Error())
        } else {
            boomer.Events.Publish("request_success","SayHello","grpc", 0.0, int64(endTime - startTime))
        }
    }
}

```
func main() {
    task :=&boomer.Task{ Name:"grpc_test", Fn:grpc_test, }
    boomer.Run(task)
}
```

我们多台主机，每个主机部署一个master或slave，无论是启动单个slave，还是启动多个slave，模拟的user数量大概在1000左右。再多则连结报错。

**Comment by zbye** [comment]
报错：
main.grpc_test()
	/usr/local/go/workspace/src/demo/main_loop.go:28 +0x220
demo/vendor/github.com/myzhan/boomer.(*runner).safeRun(0xc4202140c0, 0xab2548)
	/usr/local/go/workspace/src/demo/vendor/github.com/myzhan/boomer/runner.go:86 +0x43
demo/vendor/github.com/myzhan/boomer.(*runner).spawnGoRoutines.func1(0xc4202245a0, 0xc4202140c0, 0xab2548)
	/usr/local/go/workspace/src/demo/vendor/github.com/myzhan/boomer/runner.go:130 +0x9f
created by demo/vendor/github.com/myzhan/boomer.(*runner).spawnGoRoutines
	/usr/local/go/workspace/src/demo/vendor/github.com/myzhan/boomer/runner.go:118 +0x1c8
runtime error: invalid memory address or nil pointer dereference

**Comment by myzhan** [comment]
Hi，这样压测是可以的，不过有两点建议

1. 如果 conn 是线程安全的，不要在 grpc_test 里面建连接，再自己加一个死循环，最好把建连接挪到外面去，去掉 grpc_test 函数里面的死循环。
2. 用 boomer.RecordSuccess 和 boomer.RecordFailure 来记录测试结果。

一个主机跑一个 slave 就好了，建连接报错应该跟主机网络配置有关。具体是啥异常？可能你系统的 max open files 配置没有改大，默认是 1024。
