### ISSUE TITLE
 How to disconnect when the benchmark has finished

### ISSUE THREAD

**Issue by phamtai97** [myzhan/boomer#52]
I benchmark by reading data from file to send to server. Once I have finished I want to stop the boomer benchmark program and disconnect with the locust. Do you have any way?

**Comment by myzhan** [comment]
You can call boomer.Events.Publish("boomer:quit") to send a "quit" message to locust asynchronously, and wait for one second or more, then you can just call os.Exit()

**Comment by phamtai97** [comment]
Thanks you :+1:
