### ISSUE TITLE
Can Boomer connect to a locust address other than 127.0.0.1:5557

### ISSUE THREAD

**Issue by phamtai97** [myzhan/boomer#54]
I run locust on another address, how to make the boomer can connect to only that address. I read the code of the boomer and saw it only connect to the address 127.0.0.1:5577

**Comment by myzhan** [comment]
You can use these command-line parameters.

https://github.com/myzhan/boomer/blob/master/boomer.go#L164

**Comment by phamtai97** [comment]
I tried it but my project using lib https://github.com/urfave/cli, this lib overrided flag, so i can not use boomer's flag.

**Comment by myzhan** [comment]
I'm not familiar with this package. You can try to modify the local copy of boomer and hardcode the master address.

BTW, I'm thinking of passing those parameters in user's code, instead of command-line.
