### ISSUE TITLE
使用locust+boomer时不确定的小问题

### ISSUE THREAD

**Issue by Liuxiaojuan** [myzhan/boomer#55]
在locust+boomer的框架下有2个小问题：

1. 在locust里， 一个Locust类代表一个用户，然后可以在类变量里定义用户执行的任务集以及任务之间最大/最小等待时间，这些在boomer中的怎么体现？ 我猜想在boomer中，一个boomer实例就是一个用户，但不确定

2. 假设定义用户数是100，boomer创建100个用户之后是什么时候销毁这100个用户，是在完成一次task之后还是在测试完成之后？

**Comment by myzhan** [comment]
1. 跟 locust 不一样，boomer 并发跑的是纯函数，locust 跑的是实例方法，所以不能在实例变量里面存东西。你可以自己维护一个用户池，然后 Fn 函数从池子里面取用户实例出来跑。
2. web 页面填的值，boomer 当成并发数来看待了，你填 100，boomer 会创建 100 个 goroutine ，在一个循环里面跑 Fn 函数，你 stop 的时候，这些 goroutine 就被销毁了。

**Comment by myzhan** [comment]
See: https://github.com/myzhan/boomer/issues/39

**Comment by Liuxiaojuan** [comment]
OK，看起来我当前的用法没有问题，感谢大佬这么高效的回复
