### ISSUE TITLE
Expose runner type

### ISSUE THREAD

**Issue by Bo0mer** [myzhan/boomer#56]
Hello,

First of all, thanks for your awesome work!

I'd like to ask whether you have any plans about exposing the `runner` type, defined in `runner.go`.
As of now, there is a single instance of it, called `defaultRunner`, which can be controlled by passing flags during command startup, e.g.
```
example -maxRPS=10 -master-host=12.34.56.78
```

I find this to be limiting, becasue
* it ties me to use the Go's standard library flag package
* it is not possible to control any of the options programatically
* it is not possible to change any of the internal dependencies of the `runner`, e.g. the used logger

Please do let me know if you need any additional details.
Thanks,
Ivan

**Comment by myzhan** [comment]
Yep, I'm working on exposing a Boomer type, then you can create an instance of Boomer instead of using the default one.

See: https://github.com/myzhan/boomer/issues/54

**Comment by Bo0mer** [comment]
Thanks for the quick response. I’m willing to help so please let me know if there’s something that I could do or test.

**Comment by myzhan** [comment]
It's a huge commit, I'm try to keep backward compatibility. Please test it and send feedback :D

**Comment by Bo0mer** [comment]
Thanks, will do tomorrow or the day after tomorrow. It looks great at first glance.

**Comment by Bo0mer** [comment]
Sorry for the delay, I can confirm that the change is OK. Thanks.
