### ISSUE TITLE
./a.out --run-tasks foo,bar will panic

### ISSUE THREAD

**Issue by blackmagic02881** [myzhan/boomer#57]
./a.out --run-tasks foo,bar with the example will panic. 

anic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x16c6894]

goroutine 1 [running]:
github.com/myzhan/boomer.(*Boomer).RecordSuccess(...)
	/Users/mingzhang/go/src/github.com/myzhan/boomer/boomer.go:71
github.com/myzhan/boomer.RecordSuccess(...)
	/Users/mingzhang/go/src/github.com/myzhan/boomer/boomer.go:175
main.getService()
	/Users/mingzhang/work/locust-s3/locustfiles/go/s3.go:35 +0x154
github.com/myzhan/boomer.runTasksForTest(0xc0001605a0, 0x2, 0x2)
	/Users/mingzhang/go/src/github.com/myzhan/boomer/boomer.go:115 +0x1e3
github.com/myzhan/boomer.Run(0xc0001605a0, 0x2, 0x2)
	/Users/mingzhang/go/src/github.com/myzhan/boomer/boomer.go:130 +0x4a9
main.main()

the reason is that we have no defaultboomer created yet.

**Comment by myzhan** [comment]
Thanks, you are right :D
