### ISSUE TITLE
weight is misleading

### ISSUE THREAD

**Issue by blackmagic02881** [myzhan/boomer#58]
in the locustio python version, the weight is how frequently a task get run. for example, if someone has 2 tasks, each has weight of 1, then each get 50% of chances to run.

in Boomer, this seems to be different. what i observed is that even if i have 2 tasks, each has weight of 1, if task 1 takes average 5 ms to run while task 2 takes average 10 ms to run, then task 1 will have 2x of RPS compared with task 2. this makes it very hard to do io test when someone want to have 80% write and 20% read for example. (btw, i started writing a go version of s3 test code https://github.com/twosigma/locust-s3/blob/master/locustfiles/go/s3.go. your package is great. thank you!) 

i guess the weight here seems to how many coroutines will be initialized?  have not check boomer source code yet.

**Comment by myzhan** [comment]
The python version has two kinds of weight. The one [in the Locust object](https://github.com/locustio/locust/blob/master/locust/core.py#L129) is used to [create coroutines](https://github.com/locustio/locust/blob/master/locust/runners.py#L70). Another one [in the TaskSet object](https://github.com/locustio/locust/blob/master/locust/core.py#L225) is used to [specify the task’s execution ratio](https://github.com/locustio/locust/blob/master/locust/core.py#L418). The second one is what you want.

Boomer implements Task like the "Locust object" in the python version, so the weight is used to create goroutines. But in locust4j, the java version, I introduced TaskSet and [WeighingTaskSet](https://github.com/myzhan/locust4j/blob/master/src/main/java/com/github/myzhan/locust4j/taskset/WeighingTaskSet.java).

Feel free to send a PR if you make it happen :D

**Comment by Bo0mer** [comment]
Maybe it deserves a comment about the semantics of the value?
