### ISSUE TITLE
Locust 0.11.0 support 

### ISSUE THREAD

**Issue by mangatmodi** [myzhan/boomer#59]
**Describe the bug**
Locust 0.11.0 introduce heartbeat mechanism between master and slave. As boomer clients are required to send heartbeats, master will consider them out of sync.

**Comment by mangatmodi** [comment]
I will try to make a PR for the fix myself :)

**Comment by myzhan** [comment]
Please checkout the "dealersocket" branch :D

Because boomer has not version yet, I'm thinking of keeping compatible with locust before 0.11.0.

If it's hard to do so, we will drop support for locust 0.10.0 and before.

**Comment by mangatmodi** [comment]
I was planning it tomorrow. So hard work saved :P

**Comment by myzhan** [comment]
Good ideas are always welcome. I'll trying to rebase the "dealersocket" branch into master. It won't take long.

**Comment by myzhan** [comment]
Hi @mangatmodi , please update boomer and test.

**Comment by mangatmodi** [comment]
@myzhan Hey I totally forgot about this request. So I tested, it is working perfectly with 0.11.0. I also force killed a slave, which removed it from master. Although it is shame that it is not backward compatible and with poor versioning in Golang, many will unintentionally update boomer.

Do you think we could instead make 0.11.0 support experimental and which will be enabled only with a flag. Many libraries mark new features experimental or mark the older features as depreciated...

**Comment by myzhan** [comment]
It's possible to keep compatibility without a flag, because we can detect the remote socket type. But IMHO, it's hard to keep the code stay clean.
