### ISSUE TITLE
error exit

### ISSUE THREAD

**Issue by great2soul** [myzhan/boomer#6]
I totally followed your ReadMe to run the example main.go, but get "exit status 1". 
<img width="1079" alt="screen shot 2017-05-03 at 12 03 23 am" src="https://cloud.githubusercontent.com/assets/1615573/25627264/96b57190-2f94-11e7-9195-6624217fd8c7.png">

**Comment by myzhan** [comment]
It looks like you enabled zeromq support for locust, and ran boomer without zeromq.

You can install goczmq for boomer, and run boomer with zeromq.

Or, you can disable locust's zeromq rpc if you want to give it a try ASAP.

**Comment by great2soul** [comment]
I use all kinds of methods, but still get the wrong output.
<img width="1072" alt="screen shot 2017-05-04 at 12 00 17 am" src="https://cloud.githubusercontent.com/assets/1615573/25669747/0dd8bd18-305d-11e7-8327-6c4d7b7ffc5a.png">
<img width="1070" alt="screen shot 2017-05-03 at 11 58 31 pm" src="https://cloud.githubusercontent.com/assets/1615573/25669746/0db4d13c-305d-11e7-8eef-4964a610d705.png">

**Comment by myzhan** [comment]
It looks like goczmq fails to run. Can you provider more information about your environment?

In the meanwhile, you can disable locust's zeromq support by changing its code, and build boomer without zeromq.

You can find the init file in site-package dir of Python.
https://github.com/locustio/locust/blob/master/locust/rpc/__init__.py#L7

Use socketrpc rather than zmqrpc.

**Comment by great2soul** [comment]
I installed locust using pip. Then run the example followed http://myzhan.github.io/2016/03/01/write-a-load-testing-tool-in-golang/. Then I installed goczmq according to the instruction.
My env is OSX 10.12, python 2.7, go 1.7.

**Comment by myzhan** [comment]
OK, I will look into it. And, You can force locust to use socket rpc before this problem is solved.

**Comment by great2soul** [comment]
Thanks. I will take a try.

**Comment by great2soul** [comment]
Hi, do you know how to get the executable file from the source code of locust?

**Comment by myzhan** [comment]
Just run locust without installation from source code.

python -m locust.main -f ../boomer/dummy.py --master

**Comment by great2soul** [comment]
Thanks.

**Comment by myzhan** [comment]
I can't reproduce your problem. Have you installed all the dependencies of goczmq? They are libsodium, libzmq, czmq. And you must build libzmq with libsodium explicitly, **it's not a default option**.

<img width="659" alt="2017-05-04 10 15 49" src="https://cloud.githubusercontent.com/assets/953781/25707857/63cfd930-3117-11e7-8b01-595598da06e4.png">

How to build libzmq with libsodium?

```bash
cd libzmq-master
mkdir cmake-build && cd cmake-build
cmake -DWITH_LIBSODIUM=on ..
make && sudo make install
```

**Comment by great2soul** [comment]
I tried both socket and zeromq to run it. Failed.
<img width="833" alt="screen shot 2017-05-05 at 12 52 46 am" src="https://cloud.githubusercontent.com/assets/1615573/25715238/6d4fe5fc-312d-11e7-8da8-ba29be0836b8.png">
<img width="1073" alt="screen shot 2017-05-05 at 12 51 24 am" src="https://cloud.githubusercontent.com/assets/1615573/25715237/6d4c342a-312d-11e7-9806-d9c79d7536e1.png">

I re-installed libsodium, libzmq and czmq. Building libzmq with libsodium.
<img width="388" alt="screen shot 2017-05-05 at 12 38 02 am" src="https://cloud.githubusercontent.com/assets/1615573/25715276/91db8912-312d-11e7-9964-0f1dce9b1901.png">

I start locust with zeromq using pip installed exe and then using source code of rpcwocket(pic 2).
I specify '-tags=zeromq' or not when I build main.go to get the difference rpc version of locust slave.

I am confused about why the process was killed while I run "./a.out --rpc=zeromq"

**Comment by great2soul** [comment]
Another question. If I just start a bunch of gorutines to send web request, could the result be able to explain the server's benchmark?
What's the difference from between locust and that method?
Thanks.

**Comment by great2soul** [comment]
Thanks. 
I will make clear 1 and 2 and put the result here.

**Comment by great2soul** [comment]
I try it using another mac。 Everything goes right. Close this issue.

**Comment by zsounder** [comment]
same issues, can not run.

**Comment by myzhan** [comment]
@zsounder Please provide more informations, thx

1. Locust version?
2. error log?

Locust has removed the socket support, only use zeromq.
Currently, boomer use gomq as zeromq client, please try the latest code of  boomer.
