### ISSUE TITLE
can not connect with ubuntu 18.04

### ISSUE THREAD

**Issue by blackmagic02881** [myzhan/boomer#60]
**Describe the bug**
it looks like boomer can not connect to a locust under Ubuntu 18.04. same setup works with Ubuntu 16.04.

**To Reproduce**

run with strace. it unclear to me why it tried 5557 and immediately try to connect 5558.

strace: Process 6282 attached
2019/03/20 01:43:33 Boomer is built with gomq support.
[pid  6272] connect(3, {sa_family=AF_INET, sin_port=htons(5557), sin_addr=inet_addr("10.142.0.2")}, 16) = -1 EINPROGRESS (Operation now in progress)
[pid  6272] connect(5, {sa_family=AF_INET, sin_port=htons(5558), sin_addr=inet_addr("10.142.0.2")}, 16) = -1 EINPROGRESS (Operation now in progress)
[pid  6272] connect(5, {sa_family=AF_INET, sin_port=htons(5558), sin_addr=inet_addr("10.142.0.2")}, 16) = -1 EINPROGRESS (Operation now in progress)
[pid  6274] connect(5, {sa_family=AF_INET, sin_port=htons(5558), sin_addr=inet_addr("10.142.0.2")}, 16) = -1 EINPROGRESS (Operation now in progress)
[pid  6272] connect(5, {sa_family=AF_INET, sin_port=htons(5558), sin_addr=inet_addr("10.142.0.2")}, 16) = -1 EINPROGRESS (Operation now in progress)

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. centos]
 - Go Version: [e.g. 1.10]

**Additional context**

**Comment by myzhan** [comment]
Locust 0.11.0 changed the RPC method. If you update locust, you need to update boomer.

See: https://github.com/myzhan/boomer/issues/59

> why it tried 5557 and immediately try to connect 5558.

Because the old version of locust listens on two ports. Since the 0.11.0 version, only one port is needed.

**Comment by blackmagic02881** [comment]
i installed .11.0 under ubuntu 64 with python 3.7. it works. i am not sure if it is due to locust. maybe something else?

**Comment by myzhan** [comment]
If you are using locust 0.11.0, you should update boomer and recompile you code. Because boomer drops support for locust version before 0.11.0 yesterday.

**Comment by blackmagic02881** [comment]
that did the trick. thanks.
