### ISSUE TITLE
code seems have bug around weightSum handling 

### ISSUE THREAD

**Issue by blackmagic02881** [myzhan/boomer#61]
**Describe the bug**
tried to understand the code and this seem to be wrong

runner.go. if weightsum is possible to be 0, should we have code

	for _, task := range r.tasks {
		percent := float64(task.Weight) / float64(weightSum)
		if weightSum == 0 {
			amount = int(float64(spawnCount) / float64(len(r.tasks)))
		} else {
          		amount := int(round(float64(spawnCount)*percent, .5, 0))
                 }

instead of 
	for _, task := range r.tasks {
		percent := float64(task.Weight) / float64(weightSum)
		amount := int(round(float64(spawnCount)*percent, .5, 0))

		if weightSum == 0 {
			amount = int(float64(spawnCount) / float64(len(r.tasks)))
		}

**Comment by blackmagic02881** [comment]
oops. i think my suggestion was wrong as well. need a different one.

**Comment by blackmagic02881** [comment]
how about 
        }

        for _, task := range r.tasks {
-               percent := float64(task.Weight) / float64(weightSum)
-               amount := int(round(float64(spawnCount)*percent, .5, 0))
-
+               var amount int
                if weightSum == 0 {
                        amount = int(float64(spawnCount) / float64(len(r.tasks)))
+               } else {
+                       percent := float64(task.Weight) / float64(weightSum)
+                       amount = int(round(float64(spawnCount)*percent, .5, 0))
                }

**Comment by myzhan** [comment]
The original code works, because divided by zero will produce a NaN instead of panics.

But there is a bug indeed, if there are two tasks, one's weight is 1, the other's weight is 3, and you want to spawn 10 goroutines, you will get 11 running goroutines at last, which is not what we want.

Feel free to sent a PR to fix it.

**Comment by myzhan** [comment]
See also https://github.com/myzhan/boomer/pull/72
