### ISSUE TITLE
可以不依赖locust单独做压测工具吗？

### ISSUE THREAD

**Issue by HonniLin** [myzhan/boomer#63]
如题，公司的centor版本太低了，导致locust怎么装都用不了

**Comment by myzhan** [comment]
如果是 pyzmq 的问题，可以先用 pip 安装最低要求的 16.0.2 版本，再装 locust。

我确实有用 go 实现的 master，不过还没开源，我找个时间看看。

**Comment by HonniLin** [comment]
> 如果是 pyzmq 的问题，可以先用 pip 安装最低要求的 16.0.2 版本，再装 locust。
> 
> 我确实有用 go 实现的 master，不过还没开源，我找个时间看看。

嗯嗯，非常期待~

**Comment by HonniLin** [comment]
locust的master和 bloomer可以放在两台服务器上面吗~

**Comment by myzhan** [comment]
可以，指定一下参数。https://github.com/myzhan/boomer/blob/master/legacy.go#L85

**Comment by myzhan** [comment]
已支持 standalone 模式，详见文档。

https://boomer.readthedocs.io/en/latest/running-mode.html
