### ISSUE TITLE
Cannot build boomer tests with goczmq

### ISSUE THREAD

**Issue by gclair** [myzhan/boomer#65]
**Describe the bug**
Attempting to build one of the boomer examples (examples/http/client.go) with goczmq and unable to on multiple distros (Centos,Debian, Ubuntu).

**To Reproduce**
1. go get github.com/zeromq/goczmq
2. in boomer/examples.http ran - "go build -tags 'goczmq' .

**Expected behavior**
A build with no errors as when completed without the "-tags" argument.

**Screenshots**
```shelll
$ go build -tags 'goczmq' .
# github.com/myzhan/boomer
../../client_czmq.go:44:2: error: variables redeclared but no variable is new
  err := dealer.Connect(addr)
  ^
../../client_czmq.go:43:8: error: reference to undefined field or method ‘SetIdentity’
  dealer.SetIdentity(c.identity)
        ^
```

**Environment (please complete the following information):**
 - OS: Kubuntu 18.04.2 LTS
 - Go Version: 1.10.3 gccgo

**Additional context**
Happens on other distros as well.

**Comment by myzhan** [comment]
Thanks for reporting, now it's fixed.
