### ISSUE TITLE
slave连接上master且开始压测后，UI统计界面中没有监控数据展示

### ISSUE THREAD

**Issue by solxnp** [myzhan/boomer#66]
**Describe the bug**

**To Reproduce**
1. locust -f dummy.py --master --master-bind-host=127.0.0.1 --master-bind-port=5557
2. open "http://localhost:8089/" in browser
3. go run locustBoomer.go --master-host=127.0.0.1 --master-port=5557

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/18416053/61953694-a4e19a00-afe9-11e9-8f1a-8edae6e65a1d.png)

**Environment (please complete the following information):**
 - OS: win10
 - Go Version: go version go1.12.5 windows/amd64

**Additional context**
最小案例：
```
package main

import "github.com/myzhan/boomer"

func getInfo()  {
    url := "http://xxx"
    payload := map[string]interface{}{"xxx": "xxx"}
    res := request.Request{}
    res.Post("getInfo", url, payload)

}

func waitForQuit() {
    wg := sync.WaitGroup{}
    wg.Add(1)

    quitByMe := false
    go func() {
        c := make(chan os.Signal)
        signal.Notify(c, syscall.SIGINT, syscall.SIGTERM)
        <-c
        quitByMe = true
        globalBoomer.Quit()
        wg.Done()
    }()

    _ = boomer.Events.Subscribe("boomer:quit", func() {
        if !quitByMe {
            wg.Done()
        }
    })

    wg.Wait()
}

var globalBoomer = boomer.NewBoomer("127.0.0.1", 5557)


func main() {
    log.SetFlags(log.LstdFlags | log.Lshortfile)

    task := &boomer.Task{
        Name: "getGoodsDetail",
        Fn: getGoodsDetail,
    }

    globalBoomer.Run(task)

    waitForQuit()
    log.Println("shut down")
}
```

=====================================================
Post是这样定义的

```
func (r *Request) Post(funcName string, url string, payload map[string]interface{}) {
    
    // 调用http发起post请求

    if resp.StatusCode != 200 {
        globalBoomer.RecordFailure("http", funcName, elapsed, msg)
    } else {
        if r.ErrorCode != 200 {
            globalBoomer.RecordFailure("http", funcName, elapsed, msg)
        } else {
            // 已将响应打印出来，确认请求已正常发起
            globalBoomer.RecordSuccess("http", funcName, elapsed, responseLength)
        }
    }
}
```

**Comment by myzhan** [comment]
这个最小示例没法编译通过，slave 侧是否有打异常日志？

**Comment by solxnp** [comment]
> 这个最小示例没法编译通过，slave 侧是否有打异常日志？

slave侧未有异常日志，为确保请求正常调用，正常响应，在slave侧中将响应打印出来，除了响应，未有其他任何日志。不能编译通过是我省略了部分不重要的代码，只是为了说明结构。
请问这种情况大概会是哪里的原因，我自己尝试调调看

**Comment by myzhan** [comment]
我这边没有重现，你试试在这个地方打日志看看，定时上报结果到 master 的

https://github.com/myzhan/boomer/blob/master/stats.go#L148

**Comment by solxnp** [comment]
不好意思，上次之后就没继续关注了。
今天重新使用，发现是我自己的问题。
我将http请求部分重新封装了一个 request.go 文件，其中定义了 var globalBoomer = boomer.NewBoomer("127.0.0.1", 5557)，而 main 包中的压测用例中也定义了一个 var globalBoomer = boomer.NewBoomer("127.0.0.1", 5557)，所以最终消息其实是没有发送到 main 文件中
