### ISSUE TITLE
master 使用 --host 参数，boomer能支持么？

### ISSUE THREAD

**Issue by radiateboy** [myzhan/boomer#67]
boomer 替代slave是否也能够支持 master中的 --host参数

**Comment by myzhan** [comment]
boomer 没有自带 HTTP 压测，参考例子自己实现即可，https://github.com/myzhan/boomer/blob/master/examples/http/client.go

**Comment by radiateboy** [comment]
@myzhan 你好，我对Go语言没接触，看了下这个例子，你的意思是不是可以通过启动boomer时传url方式实现

**Comment by myzhan** [comment]
boomer 只是一个框架，没实现具体的，你压测时的协议。但是我在 examples 目录下放了一些具体的使用例子，可供参考。

使用 boomer 需要有 Go 基础，因为 Task 部分需要用户自行实现，虽然有例子可以参考。

**Comment by radiateboy** [comment]
嗯，确实使用Boomer后，测试用例的task都必须要用go来实现了，我自己做工具集成，使用locust发现rps瓶颈太明显了，相同的接口使用wrk测试有 5w rps , locust只有不到1000rps。昨天晚上发现你写的这个boomer，研究测试了下，确实突破了rps这个瓶颈。 但是往下普及，确实得案例编写人员学习Go语言。

**Comment by myzhan** [comment]
如果是通用的 http 协议，用 wrk 其实也够了。一些特殊协议的场景，例如请求要签名，要加密，这些每个项目都不同的，用 boomer 就比较合适。
