### ISSUE TITLE
RecordFailure无法统计Request per second和response time

### ISSUE THREAD

**Issue by weilang312** [myzhan/boomer#68]
if resp.StatusCode == http.StatusOK {
		boomer.RecordSuccess("GET", "/test", elapsed, resp.ContentLength)

	}
	if resp.StatusCode != http.StatusOK {
		fmt.Println("eeeee", resp.StatusCode, elapsed)
		boomer.RecordFailure("GET", "/test", elapsed, "response code fail !!!")

	}
接口返回403或400等错误，按常理是应该记录到RecordFailure中，但实际执行情况是粗我有记录进去，但无法统计到Request per second和response time，只有符合RecordSuccess才会统计数据

**Comment by myzhan** [comment]
这个其实是 locust 不算进去，如果要计算的话，你把错误的情况用 RecordSuccess 记录吧。

**Comment by weilang312** [comment]
嗯嗯，仔细拜读了下golang代码，没发现是slave的特殊处理，success和faild的逻辑都是一样的，将请求计数好后上报给master，没有做特殊处理，应该是locust那边做了展示过滤处理的
