### ISSUE TITLE
Uses 0 when hatch rate < num slave nodes

### ISSUE THREAD

**Issue by joshprzybyszewski-wf** [myzhan/boomer#69]
**Describe the bug**
When I spin up `10` slave nodes running boomer, and I have a hatchrate of `4`, the hatch rate gets rounded down to `0`, even though it should be `0.4`.

**To Reproduce**
1. Spin up 10 slave nodes running boomer.
2. Run a master dummy locust.
3. Connect to web client, request 100 users, with a hatch rate of 4.

**Expected behavior**
I would expect each boomer slave to be able to hatch at a rate of `0.4` rather than none

**Environment (please complete the following information):**
 - OS: macOS 10.13.6
 - Go Version: 1.12.9

**Additional context**
Locust calculates the float value hatch rate here: https://github.com/locustio/locust/blob/0e79c66a06702a301df4b4998d50d85dcfa41552/locust/runners.py#L313
and sends it to us here (as a float): https://github.com/locustio/locust/blob/0e79c66a06702a301df4b4998d50d85dcfa41552/locust/runners.py#L325

We receive it here as a `float64` and immediately force it to `int`: https://github.com/myzhan/boomer/blob/307abf52aca9907f857de1ed645015f22c422181/runner.go#L314

**Comment by myzhan** [comment]
Yes, you are right. I'm thinking about removing the default 'asap' hatch type and it will hatch like locust.

**Comment by myzhan** [comment]
Now it's fixed, please give it a try.

**Comment by joshprzybyszewski-wf** [comment]
Thanks! The issue is fixed, although these lines are breaking changes:

https://github.com/myzhan/boomer/commit/d64b37f1964d2ee82391cd66e8066c292c8a43b6#diff-876ef07f4e42dea5440d41057268d83dR62

https://github.com/myzhan/boomer/commit/d64b37f1964d2ee82391cd66e8066c292c8a43b6#diff-876ef07f4e42dea5440d41057268d83dL83

Thank you!
