### ISSUE TITLE
Publish函数一直在panic

### ISSUE THREAD

**Issue by tenfyzhong** [myzhan/boomer#7]
```go
boomer.Events.Publish("request_success", "query", "tcp", int64(costTime), "hello")
```

>goroutine 24 [running]:
runtime/debug.Stack(0xc42011c360, 0x1010772, 0xc4201120d0)
        /usr/local/Cellar/go/1.8.1/libexec/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /usr/local/Cellar/go/1.8.1/libexec/src/runtime/debug/stack.go:16 +0x22
github.com/myzhan/boomer.(*runner).safeRun.func1()
        /Users/zhongtenghui/go/src/github.com/myzhan/boomer/runner.go:43 +0x6e
panic(0x1472200, 0xc420110bb0)
        /usr/local/Cellar/go/1.8.1/libexec/src/runtime/panic.go:489 +0x2cf
reflect.Value.call(0x148eac0, 0x1550b28, 0x13, 0x15383c6, 0x4, 0xc42016efc0, 0x4, 0x4, 0xc420110ba0, 0xc42016efc0, ...)
        /usr/local/Cellar/go/1.8.1/libexec/src/reflect/value.go:371 +0x1094
reflect.Value.Call(0x148eac0, 0x1550b28, 0x13, 0xc42016efc0, 0x4, 0x4, 0xc42016efc0, 0x4, 0x4)
        /usr/local/Cellar/go/1.8.1/libexec/src/reflect/value.go:302 +0xa4
github.com/asaskevich/EventBus.(*EventBus).doPublish(0xc420122380, 0xc42011c330, 0x153f633, 0xf, 0xc420116a00, 0x4, 0x4)
        /Users/zhongtenghui/go/src/github.com/asaskevich/EventBus/event_bus.go:158 +0xa8
github.com/asaskevich/EventBus.(*EventBus).Publish(0xc420122380, 0x153f633, 0xf, 0xc420116a00, 0x4, 0x4)
        /Users/zhongtenghui/go/src/github.com/asaskevich/EventBus/event_bus.go:144 +0x331
main.query()
        /Users/zhongtenghui/go/src/gf.com.cn/NewQuote/secu_search/benchmark/main.go:28 +0x2e2
github.com/myzhan/boomer.(*runner).safeRun(0xc4201323c0, 0x1551f08)
        /Users/zhongtenghui/go/src/github.com/myzhan/boomer/runner.go:47 +0x43
github.com/myzhan/boomer.(*runner).spawnGoRoutines.func1(0xc420024480, 0xc4201323c0, 0x1551f08)
        /Users/zhongtenghui/go/src/github.com/myzhan/boomer/runner.go:85 +0x61
created by github.com/myzhan/boomer.(*runner).spawnGoRoutines
        /Users/zhongtenghui/go/src/github.com/myzhan/boomer/runner.go:88 +0x3d7

**Comment by myzhan** [comment]
这个字段类型传的不对，如果是 request_success 事件的话，应该是这样的。

boomer.Events.Publish("request_success", "tcp", "query", float64(costTime), int64(contentLength))

**Comment by tenfyzhong** [comment]
改成这样确实可以了。但是为什么不做好类型判断？像这样抛异常用户根本不知道是什么情况。

**Comment by myzhan** [comment]
这个异常，是 EventBus 这个依赖抛出来的。我只是捕获了异常，并打出了堆栈。像上面这种误用，你在界面上是可以看到提示的。

![image](https://user-images.githubusercontent.com/953781/26865097-c8351ca6-4b8d-11e7-837b-ad31ef0507ab.png)

**Comment by myzhan** [comment]
@tenfyzhong 你说的对，目前兼容了 float64 和 int64 两种类型的 responseTime
