### ISSUE TITLE
Task Sequence

### ISSUE THREAD

**Issue by aclowkey** [myzhan/boomer#71]
Is there a way to order tasks like TaskSequence in locust?

**Comment by myzhan** [comment]
It's easy to run in sequence, (e.g., put the code of multiple tasks in one boomer.Task), or you can implement a TaskSet like [WeighingTaskSet](https://github.com/myzhan/boomer/blob/master/taskset.go#L25)

**Comment by aclowkey** [comment]
Thanks!
