### ISSUE TITLE
How to know boomer client is ready or not?

### ISSUE THREAD

**Issue by TranNDC** [myzhan/boomer#73]
I need to start Locust test in run time so all the slaves (boomer clients) must be ready when Locust start. Is there any way to know boomer client is ready or not? @myzhan 
Many thanks!

**Comment by myzhan** [comment]
What about adding a boomer:ready event?
https://github.com/myzhan/boomer/blob/master/examples/events/subscriber.go#L23

**Comment by myzhan** [comment]
Or you can query the RESTAPI of locust to know the status of slaves.
