### ISSUE TITLE
Not support for locustio==0.14.4

### ISSUE THREAD

**Issue by GuoTengda1993** [myzhan/boomer#77]
**Describe the bug**
boomer Not support for **locustio==0.14.4** (fine with locustio==0.13.5)

**To Reproduce**
1. Run locust == 0.14.4 in master mode
2. use http client by boomer, when boomer client is running, locust report errors:  **KeyError: 'current_cpu_usage'**, this key is a new feature of locustio >=0.14.0,

**Expected behavior**
work well with locustio>=0.14.0

**Screenshots**
![image](https://user-images.githubusercontent.com/36886351/75235921-fd834a80-57f7-11ea-9068-a3f31f53fa93.png)

**Environment (please complete the following information):**
 - OS: windows 10
 - Go Version:  go1.13.4 windows/amd64

**Comment by myzhan** [comment]
Fixed! you can update boomer now.
