### ISSUE TITLE
locust + boomer 压测http2出错

### ISSUE THREAD

**Issue by yi-guo-546** [myzhan/boomer#80]
您好，我使用locust + boomer 压测http2 server时，出现如下错误。由于我对go语言了解甚少，暂时解决不了。希望能得到您的回复。
dial tcp 10.129.97.133:9995: connect: cannot assign requested address

下面是我压测的client代码：
package main

import (
    "fmt"
    "io/ioutil"
    "log"
    "net/http"
    "time"
    "crypto/x509"
    "crypto/tls"
    "github.com/myzhan/boomer"
    "golang.org/x/net/http2"
)

func getDemo() {
    start := time.Now()
    client := &http.Client{}

    caCert, err := ioutil.ReadFile("crt-server.crt")
    if err != nil {
        log.Fatalf("Reading server certificate: %s", err)
    }
    caCertPool := x509.NewCertPool()
    caCertPool.AppendCertsFromPEM(caCert)
    // Create TLS configuration with the certificate of the server
    tlsConfig := &tls.Config{RootCAs: caCertPool,}
    client.Transport = &http2.Transport{TLSClientConfig: tlsConfig,}

    resp, err := client.Get("xxxx")

    elapsed := time.Since(start)
    if err == nil {
        boomer.RecordSuccess("http2", "getFile", elapsed.Nanoseconds()/int64(time.Millisecond), resp.ContentLength)
        defer resp.Body.Close()
    } else {
        boomer.RecordFailure("http2", "getFile", elapsed.Nanoseconds()/int64(time.Millisecond), err.Error())
        fmt.Printf("%s \n", err)
    }

}

func main() {
    task := &boomer.Task{
        Name: "getFile",
        // The weight is used to distribute goroutines over multiple tasks.
        Fn:     getDemo,
    }

    boomer.Run(task)
}

**Comment by myzhan** [comment]
这个跟 HTTP2 没关系，应该是你在 getDemo 里面创建 http.Client，连接的创建和销毁太频繁导致，可以考虑用一个全局的 http.Client，参考 example 目录的例子。

**Comment by yi-guo-546** [comment]
感谢建议，问题解决了。
