### ISSUE TITLE
Boomer is built with gomq support

### ISSUE THREAD

**Issue by Super-Ps** [myzhan/boomer#82]
**Describe the bug**

**To Reproduce**
1. 根据文档步骤 更新 go get -u github.com/myzhan/boomer
2. 依赖是用的 module查看 存在 github.com/zeromq/goczmq v4.1.0+incompatible
3. 创建测试人间test1.go ，内容为文档示例
4. 执行go build -tags 'goczmq'  test1.go  提示 这3个包都没有找到，pkg-config—cflags—libczmq libzmq libna
5.后面的操作 无法进行，
6.另外 locust  --master  -f test1.py 启动之后  boomer 这边只需要执行 编译好的二进制文件就可以了吗。./test1.go ,目前正在改进locust 之前的用法，希望得到帮助

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. centos]
 - Go Version: [e.g. 1.10]

**Additional context**

**Comment by myzhan** [comment]
goczmq 和 gomq 分别是两个不同的 zeromq 库，你只要选一个就好。如果你安装不上 goczmq 所需的 C 库依赖，那直接用纯 go 实现的 gomq 就行。编译的时候去掉 goczmq 这个 tag，默认用 gomq。

**Comment by Super-Ps** [comment]
我创建一个文件，文件内容为 文档示例， 使用do module ，go mod init boomertest    ，然后go get github.com/myzhan/boomer，再更新go get -u github.com/myzhan/boomer，再按照文档上测试步骤： go run --run-tasks foo,bar，提示： Run 'go help run' for details。这个命令查了一下参数没看懂，然后我尝试直接执行我的测试文件 go run  main.go ,此时提示：2020/04/14 10:35:12 Boomer is built with gomq support.  费解的是 我明明在go.mod里面安装了依赖包的。作者指导1下子

**Comment by myzhan** [comment]
go run main.go --run-tasks foo,bar，执行一遍 task 就退出，你 go run 报错是没指定源码文件。直接go run main.go 打这个日志是正常的，我不明白问题在哪里。

**Comment by Super-Ps** [comment]
我刚才反复试了几下，暂时没有报错了，怕影响你我给删除了，按照例子我当前执行到启动 locust --master -f dummy.py ，然后不知道用什么命令和 locust的8089链接起来，我尝试了  ./a.out --master-port 8089，但还是提示：2020/04/14 10:55:47 Boomer is built with gomq support.   gomq这个玩意究竟怎么才能好

**Comment by myzhan** [comment]
这个提示本身没有问题，表示启动正常，gomq 这个依赖在你 go get github.com/myzhan/boomer 的时候就已经装好了

**Comment by Super-Ps** [comment]
谢谢~目前是成功与master 链接上， 直接  ./ XX --master-port,  下一步在模拟 基于http 请求的接口形式，或者 类似 业务嵌套的处理，boomer支持么，我在源码示例中 好像没找到。

**Comment by myzhan** [comment]
boomer 是跟业务无关的，你在 Task 里面写啥它就执行啥。所以理论上支持任何业务，只是需要额外的编码。
