### ISSUE TITLE
README out of date with examples

### ISSUE THREAD

**Issue by dewrich** [myzhan/boomer#84]
**Describe the bug**
While testing this new project, the first thing you do is follow the README.  Well, I did that and this is what I got from the main.go

ᐅ go build
# github.com/test/boomer
./main.go:18:2: undefined: boomer.RecordSuccess
./main.go:30:2: undefined: boomer.RecordFailure

**Comment by myzhan** [comment]
Did you try to use "go get" to install boomer?
