### ISSUE TITLE
RPS decrease when most of the requests return connection timeout

### ISSUE THREAD

**Issue by datngohoang** [myzhan/boomer#85]
I'm running boomer with 1 vCPU, 4Gb memory, rps set to 1000, run time 120 seconds.
In case most of the requests return connection timeout, after 120 seconds the total requests fired is only about 30% of 1000*120.
Seem like many requests are pending due to wait for timeout.

**Comment by myzhan** [comment]
I can't address this issue unless you can provide the code of your tasks to reproduce it.
