### ISSUE TITLE
是否考虑添加 host 参数的支持

### ISSUE THREAD

**Issue by asdfsx** [myzhan/boomer#86]
locust 的web ui上可以输入 host 参数，但是boomer目前好像还不支持这个参数
会考虑加上这个参数的支持吗？

**Comment by myzhan** [comment]
没仔细看，这个参数目前有什么用？

**Comment by myzhan** [comment]
这个参数目前仅提供给 locust 的 HTTP 测试场景使用，boomer 没有自带 HTTP Client 的，暂时支持不了
