### ISSUE TITLE
请问我为啥提示端口被关闭错误？

### ISSUE THREAD

**Issue by liusong1999** [myzhan/boomer#9]
大神你好，最近在折腾locust，发现rps和rt差强人意，同等条件下比loadrunner差5～10倍；所以想采用您的这个golang写的组件，但是我在使用过程中发现以下问题，还望赐教：
1.首先我按照你的方法启动了管理机：
D:\temp\code\src\github.com\myzhan\boomer>locust -f dummy.py --master --master-bind-host=10.25.24.185 --master-bind-port=5557
[2017-06-20 16:18:06,955] CNHQ-14110502N/INFO/locust.main: Starting web monitor at *:8089
[2017-06-20 16:18:06,958] CNHQ-14110502N/INFO/locust.main: Starting Locust 0.8a2
2.然后我在负载机上启动，但是提示错误：
E:\gobox>ls.out --master-host=10.25.24.185 --master-port=5557
2017/06/20 16:18:16 Boomer is built without zeromq support. We recommend you to
install the goczmq package, and build Boomer with zeromq when running in distrib
uted mode.
2017/06/20 16:18:16 Boomer is connected to master(10.25.24.185:5557) press Ctrl+
c to quit.
2017/06/20 16:18:17 read tcp 10.24.51.236:51072->10.25.24.185:5557: wsarecv: An
existing connection was forcibly closed by the remote host.

看上去是管理机主动关闭了链接的端口，我换了其他端口也是一样的，请问为什么？

**Comment by myzhan** [comment]
看起来像是 locust 用的是 zeromq，而 boomer 没有用 zeromq。你可以看看这里的讨论，https://github.com/myzhan/boomer/issues/6

locust 和 boomer 用的通信协议必须一致。

解决方法有两个：
1. 修改 locust 源码，让它使用原生的 socket，代码在 locust/rpc/__init__.py。
2. 编译 boomer 的时候，加上 zeromq 的支持。

个人建议用第一种方法，由于 boomer 的性能比较好，一般一台机器只启动一个 slave，就可以用满机器资源，无须挂很多 slave，所以用原生 socket 来和 master 通信，问题不大。

**Comment by liusong1999** [comment]
好的，我再去试一下。

**Comment by liusong1999** [comment]
myzhan老师你好，我今天尝试了很多种方法，最后没用windows而用ubuntu操作系统成功了，但是我发现用boomer作为负载机产生的rps反而更低了很多，从原来的500左右的rps降到10rps，是不是我哪里的姿势不对？以下是code，就是一个非常简单的GET请求：
package main

import "github.com/myzhan/boomer"

import (
	"io"
	"io/ioutil"
	"net/http"
)

func liusong() {

	startTime := boomer.Now()

	tr := &http.Transport{
		DisableKeepAlives: true,
	}

	client := &http.Client{Transport: tr}
	resp, err := client.Get("http://pcsstest.preing.com/pcss-web/label/poplabels.do?params=[{%22channel%22:%22WAP%22,%22cmmdtyCode%22:%22000000000100004312%22,%22labelScene%22:%2205%22,%22supplierCode%22:%220000000000%22}]")
	resp.Header.Add("User-Agent", "WafTestSpider")
	io.Copy(ioutil.Discard, resp.Body)
	resp.Body.Close()

	endTime := boomer.Now()

	if err != nil {
		boomer.Events.Publish("request_failure", "http", "liusong", 0.0, err.Error())
	} else {
		boomer.Events.Publish("request_success", "http", "liusong", float64(endTime-startTime), resp.ContentLength)
	}
}

func main() {

	task := &boomer.Task{
		Name:   "ls",
		Weight: 10,
		Fn:     liusong,
	}

	http.DefaultTransport.(*http.Transport).MaxIdleConnsPerHost = 2000

	boomer.Run(task)

}

**Comment by myzhan** [comment]
resp.Header.Add("User-Agent", "WafTestSpider") 这句代码有点问题，如果你是要修改 UA 的话，应该在发请求之前加。

除此之外，压测代码没有其它问题。需要更多的信息，来定位问题。例如只有 10 rps 的时候，你压测的并发数是多少？boomer 的 CPU 负载是多少？服务端响应是否正常？
