### ISSUE TITLE
Provide master host and port through env vars

### ISSUE THREAD

**Issue by crichardson32** [myzhan/boomer#90]
It would be nice if we could check env vars LOCUST_MASTER_NODE_HOST and LOCUST_MASTER_NODE_PORT for connection info instead of having to define it inside the tests. This would match the python clients way of passing in connection info.

**Comment by myzhan** [comment]
Boomer used to read connection info from CLI params 

https://github.com/myzhan/boomer/blob/901d7fa78bb8ad02225f83edb29544e44818b0c8/legacy.go#L83

But I prefer to use boomer as a library, you can get the connection info from anywhere you like, then pass it to boomer.

**Comment by crichardson32** [comment]
We actually already do that just figured i would make the request to keep it uniform across boomer and locust4j. but thats fine we can use the cli for it.
