### ISSUE TITLE
关于 --max-rps 参数的用法

### ISSUE THREAD

**Issue by solxnp** [myzhan/boomer#91]
在文档中我看到了 --max-rps 参数，想先咨询下这个参数的实际用途

不知道你是否用过阿里云的 PTS 商用压测工具，他们实现了一种 RPS 的压测模式，官方描述如下：
> 例如 1000 RPS 表示一秒内发出 1000 个请求。在施压过程中，根据被压测接口的 RT 表现不同，施压引擎为了达到您指定的吞吐量，会自适应调整虚拟用户数（即并发量）
>
> 当 RPS 设置为 1000，
> - 如果被压测服务 RT 为 0.1 秒，则虚拟用户数为 100；
> - 如果被压测服务 RT 为 2 秒，则虚拟用户数为 2000；
> - 以此类推

当以吞吐量作为目标时，这种方式很有用

--max-rps 是类似实现的这种功能吗？

**Comment by myzhan** [comment]
不完全类似，--max-rps 只是限制了单个 boomer 实例能达到的最大 RPS，避免做线上压测的时候，把线上压垮。类似 PTS 这个场景，我觉得在上游 locust 去实现比较合适。
