### ISSUE TITLE
Inifinite Tasks?

### ISSUE THREAD

**Issue by austink-carb** [myzhan/boomer#92]
**Describe the bug**
Unless I'm misunderstanding something (highly likely), I don't think the locust tasks should run indefinitely. In the runner.go spawnWorkers method, the goroutine is wrapper in a for {} loop that continuously calls the function pointers assigned to the task. Should all tasks end once the function has returned success/failure?

**To Reproduce**
1. Run the main.go example with 1 simulated user and 1 second hatch rate and the foo & bar methods are executed more than just once.

**Expected behavior**
I would expect the task to be executed once and exit

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Go Version: 1.13.4

**Comment by myzhan** [comment]
Yes, you misunderstood. Boomer is a library for performance test, so it will keep running tasks, unless the master tells it to stop.

**Comment by austink-carb** [comment]
So I've been searching through the library, and I don't see a way to stop a task. boomer.Quit() seems like it will stop the whole sim, but maybe we could have an optional way to stop the worker goroutine that is constantly running the task? Allowing me to keep track of how many times the task has been executed and when I've hit a limit I can stop the task.

Thank you!

**Comment by myzhan** [comment]
Most of the time, the start and stop of a task is controlled by the locust master. If you want to keep a counter of task execution, you can add a custom rate limiter to boomer. And when the threshold exceeded, it can call boomer.Quit() to stop all  task, or block them.

**Comment by austink-carb** [comment]
It would be nice if there was a way to simulate a stop from within the code instead of only from the locust master web interface. There may be cases where we know the tests are done and we would like to simulate hitting the "stop" button on the web ui so everything is updated accordingly. Is that a valid ask for the next version update?

**Comment by myzhan** [comment]
The "num users simulate" field means concurrency, in boomer, it's the number of goroutines. If you tell locust to spawn 5000 users, boomer will spawn 5000 goroutines to run you tasks until you stop the test. If you want to control the total number of requests, you can add a custom  rate limiter to boomer, which can block the execution of tasks when the threshold exceeded.

**Comment by austink-carb** [comment]
Will this also stop the test? I still haven't found a way to stop the test and keep the work connected.

**Comment by austink-carb** [comment]
Also... does this mean that if anyone wants to[ use locust for CI](https://docs.locust.io/en/stable/running-locust-without-web-ui.html), that boomer won't work because the tasks just run forever and the locust master never knows when the work has completed its' swarm?
