### ISSUE TITLE
prometheus_exporter.py 启动还是进入原生的locust

### ISSUE THREAD

**Issue by lihuacai168** [myzhan/boomer#97]
**复现步骤*
1.clone本项目
2.在项目根目录执行 `locust --master -f prometheus_exporter.py`
![image](https://user-images.githubusercontent.com/11568297/88570967-889a9200-d06f-11ea-8c53-e20712a226df.png)

**Expected behavior**
期望是进入prometheus页面,实际进入原生的locust页面

**Screenshots**

![image](https://user-images.githubusercontent.com/11568297/88570502-c0550a00-d06e-11ea-95dd-cc94850c3373.png)

**Environment (please complete the following information):**
 - OS: macOS 10.15.5
 - Go Version: 1.14.4
 - Py Version: 3.8.2

**Comment by myzhan** [comment]
这个只是开了一个接口，提供给 prometheus 采集数据，并不涉及 prometheus 页面。
