### ISSUE TITLE
rateLimitEnabled开启且block时，会丢弃task

### ISSUE THREAD

**Issue by eyotang** [myzhan/boomer#99]
**Describe the bug**
rateLimitEnabled开启且block时，会丢弃task

**To Reproduce**
1. 本地NewStableRateLimiter为每秒一个请求
2. NewStandaloneBoomer设置1个用户，1秒完成孵化
3. 设置SetRateLimiter

**Expected behavior**
随机获取的task，不会丢弃

**Screenshots**
随机获取的task，被丢弃了。

**Environment (please complete the following information):**
 - OS: [e.g. centos]
 - Go Version: [e.g. 1.10]

**Additional context**
for {
					task := r.getTask()
					select {
					case <-quit:
						return
					default:
						if r.rateLimitEnabled {
							blocked := r.rateLimiter.Acquire()
							if !blocked { << 此处会跳过上面获取的task
								r.safeRun(task.Fn)
							}
						} else {
							r.safeRun(task.Fn)
						}
					}
				}

**Comment by myzhan** [comment]
设计上是这样，压测场景，每个 task 都会被执行很多次，允许丢弃单次执行。

**Comment by eyotang** [comment]
这样设计，会导致，随机性没法保证。

**Comment by eyotang** [comment]
![image](https://user-images.githubusercontent.com/2398680/96567998-07633c00-12fa-11eb-81c6-2b88ec4fe54c.png)
这样实现，会更合理一些。

**Comment by myzhan** [comment]
你是说，先走限流逻辑，再去获取 task？也可以的，可以提一个 PR 过来。

**Comment by eyotang** [comment]
修复：先限流，再获取task #102
